//! `contract-gen`: every file K2 generates from the verb catalog
//! (prd-zen-user-widgets-v2 UWA4, UWA5, UWA9, UWA11, UWB28).
//!
//! Outputs, all rendered in memory by [`render`]:
//! - `src/renderer/lib/zen/zen-verbs.generated.ts`: `ZEN_VERBS` (every row
//!   with a `builtin` or `registered` renderer binding, verb → cap) and
//!   `ZEN_CUSTOM_VERBS` (rows exposed to `widget`).
//! - `src/renderer/lib/k2-caps.generated.ts`: the shared cap table.
//! - `sdk/generated/k2.d.ts`: types for the frame's `k2` object.
//! - `sdk/generated/k2-frame.js`: the widget verb table joined with the
//!   shared runtime `sdk/k2-runtime.js` into one classic script.
//! - `sdk/generated/contract-snapshot.json`: sha256 of the catalog, the
//!   runtime and every output, for the vitest twin of the freshness test.
//! - The fenced `k2 zen guide api` block in `cli/k2`.
//!
//! The bin (`cargo run -p k2-core --bin contract-gen`) writes them; the
//! freshness test below renders them again and fails on any difference. It
//! never rewrites a file itself. Nobody edits an output by hand.

use std::collections::BTreeMap;

use serde_json::Value as J;
use sha2::{Digest, Sha256};

use super::lint::request_items;
use super::{Catalog, Exposure, RendererImpl, VerbKind, VerbRow, CATALOG_JSON, CATALOG_PATH};

/// Where each output lives, relative to the repo root.
pub const ZEN_VERBS_TS: &str = "src/renderer/lib/zen/zen-verbs.generated.ts";
pub const CAPS_TS: &str = "src/renderer/lib/k2-caps.generated.ts";
pub const K2_DTS: &str = "sdk/generated/k2.d.ts";
pub const K2_FRAME_JS: &str = "sdk/generated/k2-frame.js";
pub const SNAPSHOT_JSON: &str = "sdk/generated/contract-snapshot.json";
/// The shared runtime (owner: the renderer builder). Optional: until it
/// exists, `k2-frame.js` holds only the verb table.
pub const RUNTIME_JS: &str = "sdk/k2-runtime.js";
pub const CLI: &str = "cli/k2";

/// The fence around the generated guide page in `cli/k2`.
pub const CLI_BEGIN: &str = "# >>> generated by contract-gen: zen guide api";
pub const CLI_END: &str = "# <<< generated";

/// What to run when an output is stale.
pub const REGEN: &str = "run `cargo run -p k2-core --bin contract-gen`";

/// The frame script's size cap (UWA5).
pub const FRAME_MAX_BYTES: usize = 16 * 1024;

/// The guide page's line cap (FC33).
pub const GUIDE_MAX_LINES: usize = 80;

/// Error codes every call may answer; the guide states them once.
pub const ALWAYS_ERRORS: &[&str] = &["cap_not_granted", "verb_unavailable", "failed"];

/// The ten examples `k2 zen guide api` opens with. Each uses only helpers
/// the widget table has, or the runtime's own members (a test checks).
pub const GUIDE_EXAMPLES: &[&str] = &[
    "const off = k2.agents.subscribe((rows) => draw(rows))   // live, in scope",
    "el.textContent = row.label                              // never innerHTML",
    "await k2.conversation.open(row.address)  // the Conversation beside follows",
    "k2.thread.subscribe(row.address, (v) => drawPage(v.items, v.turn))",
    "const page = await k2.thread.read(row.address, {beforeSeq: first.seq})",
    "await k2.thread.post(row.address, 'How is it going?')",
    "if (k2.can('thread.post')) showSendButton()",
    "k2.theme.changed(({theme}) => paint(theme.vars))",
    "img.src = k2.asset('cat.png')                   // a file in the folder",
    "k2.ready()                                     // once, after first draw",
];

/// Members of the frame's `k2` object that aren't catalog helpers.
pub const RUNTIME_MEMBERS: &[&str] = &["call", "subscribe", "on", "can", "ready", "config", "widget", "asset", "motion"];

/// One rendered file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Output {
    pub path: &'static str,
    pub text: String,
}

/// Every output. `runtime` is `sdk/k2-runtime.js` when it exists. The
/// `cli/k2` entry is only the fenced block (markers included).
pub fn render(c: &Catalog, runtime: Option<&str>) -> Result<Vec<Output>, String> {
    let probs = super::lint::lint(c);
    if !probs.is_empty() {
        return Err(format!("{CATALOG_PATH} doesn't lint clean:\n{}", probs.join("\n")));
    }
    let mut out = vec![
        Output { path: ZEN_VERBS_TS, text: zen_verbs_ts(c) },
        Output { path: CAPS_TS, text: caps_ts(c) },
        Output { path: K2_DTS, text: k2_dts(c)? },
        Output { path: K2_FRAME_JS, text: frame_js(c, runtime) },
        Output { path: CLI, text: cli_block(c) },
    ];
    let snapshot = snapshot_json(c, runtime, &out);
    out.push(Output { path: SNAPSHOT_JSON, text: snapshot });
    Ok(out)
}

/// The fenced block's text inside a whole `cli/k2`, markers included.
pub fn cli_block_in(cli: &str) -> Result<&str, String> {
    let start = cli.find(CLI_BEGIN).ok_or_else(|| format!("{CLI} has no '{CLI_BEGIN}' line"))?;
    let rest = &cli[start..];
    let end = rest.find(CLI_END).ok_or_else(|| format!("{CLI} has no '{CLI_END}' line after the begin marker"))?;
    let end_line = rest[end..].find('\n').map(|i| end + i + 1).unwrap_or(rest.len());
    Ok(&rest[..end_line])
}

/// `cli` with its fenced block replaced by `block`.
pub fn splice_cli(cli: &str, block: &str) -> Result<String, String> {
    let old = cli_block_in(cli)?;
    let at = cli.find(old).expect("block was found in cli");
    Ok(format!("{}{}{}", &cli[..at], block, &cli[at + old.len()..]))
}

pub fn sha256_hex(bytes: &[u8]) -> String {
    let d = Sha256::digest(bytes);
    d.iter().map(|b| format!("{b:02x}")).collect()
}

// ── Shared helpers (also read by the k2-zen skill) ───────────────────────

fn ts_str(s: &str) -> String {
    if s.contains('\'') && !s.contains('"') {
        format!("\"{}\"", s.replace('\\', "\\\\"))
    } else {
        format!("'{}'", s.replace('\\', "\\\\").replace('\'', "\\'"))
    }
}

/// Object keys in byte order, whatever map the JSON parser keeps, so the
/// outputs never depend on serde_json's `preserve_order` feature.
fn sorted_keys(m: &serde_json::Map<String, J>) -> Vec<String> {
    let mut k: Vec<String> = m.keys().cloned().collect();
    k.sort();
    k
}

fn arg_title(a: &J) -> &str {
    a.get("title").and_then(J::as_str).unwrap_or("arg")
}

fn arg_optional(a: &J) -> bool {
    a.get("default").is_some()
}

/// How a verb reads in prose: `thread.read(address, {beforeSeq, limit})`,
/// `controls.bind(kind, element, gardenId?)`, `agents.subscribe(cb)`.
pub fn signature(v: &VerbRow) -> String {
    let mut args: Vec<String> = request_items(v)
        .iter()
        .map(|a| {
            let props = a.get("properties").and_then(J::as_object).filter(|p| !p.is_empty());
            match props {
                Some(p) => format!("{{{}}}", sorted_keys(p).join(", ")),
                None if arg_optional(a) => format!("{}?", arg_title(a)),
                None => arg_title(a).to_string(),
            }
        })
        .collect();
    if matches!(v.kind, VerbKind::Subscribe | VerbKind::Event) {
        args.push("cb".into());
    }
    format!("{}({})", v.verb, args.join(", "))
}

/// Rows with a `builtin` or `registered` renderer binding: today's
/// `ZEN_VERBS`, in catalog order.
pub fn bridge_rows(c: &Catalog) -> Vec<&VerbRow> {
    c.verbs
        .iter()
        .filter(|v| {
            matches!(
                v.bindings.renderer.as_ref().map(|r| r.implementation),
                Some(RendererImpl::Builtin | RendererImpl::Registered)
            )
        })
        .collect()
}

/// Widget rows grouped by cap: no cap first, then the cap table's order.
pub fn widget_groups(c: &Catalog) -> Vec<(Option<&str>, Vec<&VerbRow>)> {
    let rows = c.verbs_exposed_to(Exposure::Widget);
    let mut out: Vec<(Option<&str>, Vec<&VerbRow>)> = Vec::new();
    let mut keys: Vec<Option<&str>> = vec![None];
    keys.extend(c.caps.iter().map(|cap| Some(cap.name.as_str())));
    for k in keys {
        let group: Vec<&VerbRow> = rows.iter().copied().filter(|v| v.cap.as_deref() == k).collect();
        if !group.is_empty() {
            out.push((k, group));
        }
    }
    out
}

fn generated_header(comment: &str, what: &str) -> String {
    format!(
        "{comment} GENERATED by contract-gen from {CATALOG_PATH}{what}.\n\
         {comment} Do not edit: change the catalog, then {REGEN}\n\
         {comment} (prd-zen-user-widgets-v2 UWA11). The freshness tests fail on drift.\n"
    )
}

// ── zen-verbs.generated.ts ───────────────────────────────────────────────

fn zen_verbs_ts(c: &Catalog) -> String {
    let mut s = generated_header("//", "");
    s.push_str("\nimport type { CatalogReach, CatalogVerbKind } from '../contract/catalog-types'\n\n");
    s.push_str("/** The catalog version this table was generated from. */\n");
    s.push_str(&format!("export const ZEN_CATALOG_VERSION = {}\n\n", c.catalog_version));
    s.push_str(
        "/**\n * Every catalog row with a `builtin` or `registered` renderer binding,\n * verb → cap (UWA4). The renderer's bridge table for K2's own widgets.\n */\nexport const ZEN_VERBS = {\n",
    );
    for v in bridge_rows(c) {
        let cap = v.cap.as_deref().map(ts_str).unwrap_or_else(|| "null".into());
        s.push_str(&format!("  {}: {cap},\n", ts_str(&v.verb)));
    }
    s.push_str("} as const satisfies Record<string, string | null>\n\n");
    let caps = c.caps_exposed_to(Exposure::Widget).iter().map(|x| ts_str(x)).collect::<Vec<_>>().join(" | ");
    s.push_str("/** One custom-widget verb: its cap, portable or local, and how it answers. */\n");
    s.push_str("export interface ZenCustomVerbRow {\n");
    s.push_str(&format!("  readonly cap: {caps} | null\n"));
    s.push_str("  readonly reach: CatalogReach\n  readonly kind: CatalogVerbKind\n}\n\n");
    s.push_str(
        "/**\n * The custom-widget allowlist (UW16, UWB10): catalog rows whose `exposure`\n * includes `widget`, grouped by cap. Its own table, never `ZEN_VERBS`.\n */\nexport const ZEN_CUSTOM_VERBS = {\n",
    );
    for (_, rows) in widget_groups(c) {
        for v in rows {
            let cap = v.cap.as_deref().map(ts_str).unwrap_or_else(|| "null".into());
            s.push_str(&format!(
                "  {}: {{ cap: {cap}, reach: {}, kind: {} }},\n",
                ts_str(&v.verb),
                ts_str(reach_name(v)),
                ts_str(kind_name(v.kind))
            ));
        }
    }
    s.push_str("} as const satisfies Record<string, ZenCustomVerbRow>\n\n");
    s.push_str("export type ZenCustomVerb = keyof typeof ZEN_CUSTOM_VERBS\n");
    s
}

fn reach_name(v: &VerbRow) -> &'static str {
    match v.reach {
        super::Reach::Portable => "portable",
        super::Reach::Local => "local",
    }
}

fn kind_name(k: VerbKind) -> &'static str {
    match k {
        VerbKind::Call => "call",
        VerbKind::Subscribe => "subscribe",
        VerbKind::Event => "event",
    }
}

fn exposure_name(e: &Exposure) -> &'static str {
    match e {
        Exposure::Widget => "widget",
        Exposure::App => "app",
    }
}

// ── k2-caps.generated.ts ─────────────────────────────────────────────────

fn caps_ts(c: &Catalog) -> String {
    let mut s = generated_header("//", " (`caps`)");
    s.push_str(
        "// Read by Settings → Apps (`label`, UWA9) and the guide.\n\n",
    );
    s.push_str("import type { CatalogExposure } from './contract/catalog-types'\n\n");
    s.push_str(
        "export interface K2CapInfo {\n  readonly label: string\n  /** A plain sentence for the cap; `{where}` is the agents' words. */\n  readonly sentence?: string\n  readonly exposure: readonly CatalogExposure[]\n}\n\n",
    );
    s.push_str("export const K2_CAPS = {\n");
    for cap in &c.caps {
        let exposure = cap.exposure.iter().map(|e| ts_str(exposure_name(e))).collect::<Vec<_>>().join(", ");
        match &cap.sentence {
            Some(sentence) => s.push_str(&format!(
                "  {}: {{\n    label: {},\n    sentence: {},\n    exposure: [{exposure}],\n  }},\n",
                ts_str(&cap.name),
                ts_str(&cap.label),
                ts_str(sentence)
            )),
            None => s.push_str(&format!(
                "  {}: {{ label: {}, exposure: [{exposure}] }},\n",
                ts_str(&cap.name),
                ts_str(&cap.label)
            )),
        }
    }
    s.push_str("} as const satisfies Record<string, K2CapInfo>\n\n");
    s.push_str("export type K2Cap = keyof typeof K2_CAPS\n\n");
    let widget = c.caps_exposed_to(Exposure::Widget).iter().map(|x| ts_str(x)).collect::<Vec<_>>().join(", ");
    s.push_str("/** Caps a custom widget may ask for (= the Rust `USER_WIDGET_CAPS`). */\n");
    s.push_str(&format!("export const USER_WIDGET_CAPS = [{widget}] as const\n\n"));
    s.push_str("export type UserWidgetCap = (typeof USER_WIDGET_CAPS)[number]\n");
    s
}

// ── k2.d.ts ──────────────────────────────────────────────────────────────

fn types_of(s: &J) -> Vec<&str> {
    match s.get("type") {
        Some(J::String(t)) => vec![t.as_str()],
        Some(J::Array(a)) => a.iter().filter_map(J::as_str).collect(),
        _ => Vec::new(),
    }
}

/// Named interfaces, in first-use order.
#[derive(Default)]
struct Ts {
    order: Vec<String>,
    bodies: BTreeMap<String, String>,
}

impl Ts {
    /// The TypeScript type of `s`. A titled object becomes a named
    /// interface (registered once).
    fn ty(&mut self, s: &J) -> Result<String, String> {
        if let Some(e) = s.get("enum").and_then(J::as_array) {
            let lits: Vec<String> = e
                .iter()
                .map(|x| match x {
                    J::String(v) => ts_str(v),
                    _ => "null".into(),
                })
                .collect();
            return Ok(lits.join(" | "));
        }
        let types = types_of(s);
        if types.is_empty() {
            return Ok("unknown".into());
        }
        let nullable = types.contains(&"null");
        let mut parts: Vec<String> = Vec::new();
        for t in types.iter().filter(|t| **t != "null") {
            parts.push(match *t {
                "string" => "string".into(),
                "number" | "integer" => "number".into(),
                "boolean" => "boolean".into(),
                "array" => {
                    let item = match s.get("items") {
                        Some(i) => self.ty(i)?,
                        None => "unknown".into(),
                    };
                    if item.contains(' ') {
                        format!("Array<{item}>")
                    } else {
                        format!("{item}[]")
                    }
                }
                "object" => self.object(s)?,
                other => return Err(format!("no TypeScript for type '{other}'")),
            });
        }
        if parts.is_empty() {
            parts.push("null".into());
        } else if nullable {
            parts.push("null".into());
        }
        Ok(parts.join(" | "))
    }

    fn object(&mut self, s: &J) -> Result<String, String> {
        let props = s.get("properties").and_then(J::as_object);
        let Some(props) = props else {
            return Ok(match s.get("additionalProperties") {
                Some(m) if m.is_object() => format!("Record<string, {}>", self.ty(m)?),
                _ => "Record<string, unknown>".into(),
            });
        };
        let required: Vec<&str> =
            s.get("required").and_then(J::as_array).map(|a| a.iter().filter_map(J::as_str).collect()).unwrap_or_default();
        let title = s.get("title").and_then(J::as_str);
        let indent = if title.is_some() { "  " } else { "" };
        let mut fields = Vec::new();
        for k in sorted_keys(props) {
            let p = &props[k.as_str()];
            let t = self.ty(p)?;
            let opt = if required.contains(&k.as_str()) { "" } else { "?" };
            let doc = p.get("description").and_then(J::as_str).map(|d| format!("{indent}/** {d} */\n")).unwrap_or_default();
            if title.is_some() {
                fields.push(format!("{doc}  readonly {k}{opt}: {t}"));
            } else {
                fields.push(format!("{k}{opt}: {t}"));
            }
        }
        match title {
            Some(name) => {
                if !self.bodies.contains_key(name) {
                    // A schema's `description` describes the property that holds
                    // it, so it is written there, never on the interface.
                    let body = format!("export interface {name} {{\n{}\n}}\n", fields.join("\n"));
                    self.order.push(name.to_string());
                    self.bodies.insert(name.to_string(), body);
                }
                Ok(name.to_string())
            }
            None => Ok(format!("{{ {} }}", fields.join("; "))),
        }
    }

    /// An argument's type: its `title` is its name, never a type name.
    fn arg(&mut self, a: &J) -> Result<String, String> {
        let mut a = a.clone();
        if let Some(o) = a.as_object_mut() {
            o.remove("title");
        }
        self.ty(&a)
    }
}

fn helper_doc(v: &VerbRow) -> String {
    let cap = v.cap.as_deref().map(|c| format!("cap {c}")).unwrap_or_else(|| "no cap".into());
    format!("  /** {} {cap} · {} · {}. e.g. `{}` */\n", v.doc, reach_name(v), v.feature, v.example)
}

fn k2_dts(c: &Catalog) -> Result<String, String> {
    let mut ts = Ts::default();
    let mut verbs_map = Vec::new();
    let mut surfaces: BTreeMap<&str, Vec<String>> = BTreeMap::new();
    let mut surface_order: Vec<&str> = Vec::new();
    let mut call_verbs = Vec::new();
    let mut sub_verbs = Vec::new();
    for (_, rows) in widget_groups(c) {
        for v in rows {
            let mut args = Vec::new();
            for a in request_items(v) {
                let t = ts.arg(a)?;
                let opt = if arg_optional(a) { "?" } else { "" };
                args.push(format!("{}{opt}: {t}", arg_title(a)));
            }
            let value = ts.ty(&v.response)?;
            verbs_map.push(format!("  {}: {{ args: [{}]; value: {value} }}", ts_str(&v.verb), args.join(", ")));
            let (surface, action) = v.verb.split_once('.').expect("lint checked surface.action");
            if !surface_order.contains(&surface) {
                surface_order.push(surface);
            }
            let method = match v.kind {
                VerbKind::Call => {
                    call_verbs.push(ts_str(&v.verb));
                    format!("  {action}({}): Promise<{value}>", args.join(", "))
                }
                VerbKind::Subscribe | VerbKind::Event => {
                    sub_verbs.push(ts_str(&v.verb));
                    let mut a = args.clone();
                    a.push(format!("cb: (value: {value}) => void"));
                    a.push("onError?: (error: K2Error) => void".into());
                    format!("  {action}({}): () => void", a.join(", "))
                }
            };
            surfaces.entry(surface).or_default().push(format!("{}{method}", helper_doc(v)));
        }
    }
    let mut s = generated_header("//", "");
    s.push_str(
        "//\n// The `k2` object a custom Garden widget gets in its sealed frame\n// (prd-zen-user-widgets-v2 §7). Named helpers are one per catalog row exposed\n// to `widget`; `k2.call` / `k2.subscribe` reach the same verbs by name.\n\nexport {}\n\n",
    );
    for name in &ts.order {
        s.push_str(&ts.bodies[name]);
        s.push('\n');
    }
    let caps = c.caps_exposed_to(Exposure::Widget).iter().map(|x| ts_str(x)).collect::<Vec<_>>().join(" | ");
    s.push_str(&format!("/** A cap a widget may ask for. */\nexport type K2Cap = {caps}\n\n"));
    let codes = c.errors.iter().map(|e| ts_str(&e.code)).collect::<Vec<_>>().join(" | ");
    s.push_str(&format!("/** The shared error codes (UWA10). */\nexport type K2ErrorCode = {codes}\n\n"));
    s.push_str(
        "/** A refused call rejects with this. */\nexport interface K2Error extends Error {\n  readonly name: 'K2Error'\n  readonly code: K2ErrorCode\n  readonly verb: string\n  readonly cap?: string\n  readonly room?: string\n  readonly feature?: string\n}\n\n",
    );
    s.push_str(&format!(
        "/** Every widget verb: its arguments and what it answers (or pushes). */\nexport interface K2Verbs {{\n{}\n}}\n\n",
        verbs_map.join("\n")
    ));
    s.push_str(&format!("export type K2Verb = keyof K2Verbs\nexport type K2CallVerb = {}\nexport type K2SubscribeVerb = {}\n\n", call_verbs.join(" | "), sub_verbs.join(" | ")));
    s.push_str("export interface K2 {\n");
    for surface in &surface_order {
        s.push_str(&format!("  readonly {surface}: {{\n"));
        for m in &surfaces[surface] {
            for line in m.lines() {
                s.push_str(&format!("  {line}\n"));
            }
        }
        s.push_str("  }\n");
    }
    s.push_str(
        "  /** Any widget verb by name; a refused call rejects with K2Error. */\n  call<V extends K2CallVerb>(verb: V, ...args: K2Verbs[V]['args']): Promise<K2Verbs[V]['value']>\n  /** Subscribe by name; returns the unsubscribe. A refused subscription ends and calls `onError` (the function after `cb`) once with a K2Error; with no `onError` K2 logs it as an uncaught error. */\n  subscribe<V extends K2SubscribeVerb>(\n    verb: V,\n    ...args:\n      | [...K2Verbs[V]['args'], (value: K2Verbs[V]['value']) => void]\n      | [...K2Verbs[V]['args'], (value: K2Verbs[V]['value']) => void, (error: K2Error) => void]\n  ): () => void\n  /** Alias of `subscribe`. */\n  on: K2['subscribe']\n  /** Drawing advice: the verb exists, its cap was allowed and K2 here has its feature. K2 still checks every call. */\n  can(verb: string): boolean\n  /** Tell K2 you have drawn (call once). */\n  ready(): void\n  /** The placement's `config` table from the Garden file. */\n  readonly config: Readonly<Record<string, string | number | boolean>>\n  readonly widget: { readonly id: string; readonly name: string; readonly garden: string }\n  /** A file in the widget's folder as a data: URL, or null. */\n  asset(name: string): string | null\n  readonly motion: { readonly reduced: boolean }\n}\n\ndeclare global {\n  const k2: K2\n  interface Window {\n    readonly k2: K2\n  }\n}\n",
    );
    Ok(s)
}

// ── k2-frame.js ──────────────────────────────────────────────────────────

fn frame_js(c: &Catalog, runtime: Option<&str>) -> String {
    let mut s = generated_header("//", " and sdk/k2-runtime.js");
    s.push_str(
        "// The shared runtime joined with the catalog's widget verb table: one\n// classic script, injected first in every custom widget frame and nonced\n// (UWA5). The runtime reads the table as `K2_CONTRACT`.\n(function () {\n  'use strict'\n",
    );
    let codes = c.errors.iter().map(|e| ts_str(&e.code)).collect::<Vec<_>>().join(", ");
    s.push_str(&format!(
        "  var K2_CONTRACT = Object.freeze({{\n    catalogVersion: {},\n    errors: Object.freeze([{codes}]),\n    verbs: Object.freeze({{\n",
        c.catalog_version
    ));
    for (_, rows) in widget_groups(c) {
        for v in rows {
            let cap = v.cap.as_deref().map(ts_str).unwrap_or_else(|| "null".into());
            s.push_str(&format!(
                "      {}: Object.freeze({{ cap: {cap}, reach: {}, kind: {}, feature: {} }}),\n",
                ts_str(&v.verb),
                ts_str(reach_name(v)),
                ts_str(kind_name(v.kind)),
                ts_str(&v.feature)
            ));
        }
    }
    s.push_str("    }),\n  })\n");
    match runtime {
        Some(rt) => {
            s.push_str(&format!("  // ---- {RUNTIME_JS} ----\n"));
            for line in rt.lines() {
                if line.is_empty() {
                    s.push('\n');
                } else {
                    s.push_str(&format!("  {line}\n"));
                }
            }
        }
        None => s.push_str(&format!("  // {RUNTIME_JS} isn't in this tree yet: the table only.\n  void K2_CONTRACT\n")),
    }
    s.push_str("})()\n");
    s
}

// ── k2 zen guide api ─────────────────────────────────────────────────────

/// The guide page text (no shell wrapping).
pub fn guide_api_page(c: &Catalog) -> String {
    let mut s = String::new();
    s.push_str("k2 zen guide api — the k2 object in a custom widget\n\n");
    s.push_str(&format!(
        "A custom widget is a sealed page in a Garden: no network, no storage, no\n\
files. It reaches K2 only through window.k2. Each call needs a cap its\n\
manifest.json asks for; a widget in your own Garden gets every one it asks\n\
for at once (no review). From K2's verb catalog, version {}.\n\n",
        c.catalog_version
    ));
    s.push_str("TEN EXAMPLES\n");
    for e in GUIDE_EXAMPLES {
        s.push_str(&format!("  {e}\n"));
    }
    s.push_str(
        "\nEVERY HELPER, BY CAP (portable: the same call works in an App later;\n\
local: Garden only). Each line: helper, reach, feature, example, [errors]\n",
    );
    let groups = widget_groups(c);
    let w_sig = groups.iter().flat_map(|(_, r)| r.iter()).map(|v| signature(v).len()).max().unwrap_or(0) + 3;
    let w_feat = groups.iter().flat_map(|(_, r)| r.iter()).map(|v| v.feature.len()).max().unwrap_or(0);
    for (cap, rows) in &groups {
        let sentence = cap.and_then(|n| c.cap(n)).map(|r| format!(" ({})", r.label)).unwrap_or_default();
        s.push_str(&format!("{}{sentence}\n", cap.unwrap_or("no cap")));
        for v in rows {
            let errs: Vec<&str> = v.errors.iter().map(String::as_str).filter(|e| !ALWAYS_ERRORS.contains(e)).collect();
            let errs = if errs.is_empty() { String::new() } else { format!("  [{}]", errs.join(" ")) };
            s.push_str(&format!(
                "  {:<w_sig$} {:<8} {:<w_feat$}  {}{errs}\n",
                format!("k2.{}", signature(v)),
                reach_name(v),
                v.feature,
                v.example
            ));
        }
    }
    s.push_str(&format!("\nEvery call may also fail with {}.\n\n", ALWAYS_ERRORS.join(", ")));
    for line in [
        "ALSO ON k2",
        "  k2.call(verb, ...args), k2.subscribe(verb, ...args, cb) (alias k2.on):",
        "  the same verbs by name. k2.can(verb): advice for drawing; K2 still",
        "  checks every call. k2.ready() once drawn. k2.config, k2.widget,",
        "  k2.asset(name), k2.motion.reduced. A refused call rejects with K2Error",
        "  (.code, .message, .verb, .cap, .room, .feature). Subscribes return the",
        "  unsubscribe; pass onError after cb (k2.thread.subscribe(addr, cb,",
        "  onError)) to hear a refused subscription (it ends; without onError K2",
        "  logs it as a widget error).",
        "",
        "RULES",
        "  textContent for anything an agent wrote, never innerHTML. No onclick=:",
        "  use addEventListener in a script file. Files via k2.asset(). Check with",
        "  k2 zen validate --widget <name>; it works as soon as it's placed.",
        "  Posting pauses after 120 posts (or 20 identical ones to one agent) in",
        "  10 minutes, until the person clicks Resume on the widget (sending_off).",
        "",
        "Types: sdk/generated/k2.d.ts in the K2 repo. Caps in K2's words: the",
        "k2-zen skill.",
    ] {
        s.push_str(line);
        s.push('\n');
    }
    s
}

fn cli_block(c: &Catalog) -> String {
    let page = guide_api_page(c);
    assert!(!page.contains("\nEOF\n"), "the guide page can't hold a heredoc terminator");
    format!(
        "{CLI_BEGIN} (do not edit; {REGEN})\n\
_zen_guide_page_api() {{\n    cat <<'EOF'\n{page}EOF\n}}\n{CLI_END}\n"
    )
}

// ── contract-snapshot.json ───────────────────────────────────────────────

fn snapshot_json(c: &Catalog, runtime: Option<&str>, outs: &[Output]) -> String {
    // Written by hand (not a serde Map) so the key order never depends on
    // serde_json's features.
    let q = |s: &str| J::String(s.to_string()).to_string();
    let mut files: Vec<(&str, String)> = outs.iter().map(|o| (o.path, sha256_hex(o.text.as_bytes()))).collect();
    files.sort();
    let runtime = runtime.map(|r| q(&sha256_hex(r.as_bytes()))).unwrap_or_else(|| "null".into());
    let files = files.iter().map(|(p, h)| format!("    {}: {}", q(p), q(h))).collect::<Vec<_>>().join(",\n");
    format!(
        "{{\n  \"generatedBy\": \"contract-gen\",\n  \"regen\": \"cargo run -p k2-core --bin contract-gen\",\n  \"catalogVersion\": {},\n  \"catalogSha256\": {},\n  \"runtimeSha256\": {runtime},\n  \"files\": {{\n{files}\n  }}\n}}\n",
        c.catalog_version,
        q(&sha256_hex(CATALOG_JSON.as_bytes())),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::contract::catalog;
    use std::path::PathBuf;

    fn root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
    }

    fn read(rel: &str) -> String {
        std::fs::read_to_string(root().join(rel)).unwrap_or_else(|e| panic!("read {rel}: {e}; {REGEN}"))
    }

    fn runtime() -> Option<String> {
        let p = root().join(RUNTIME_JS);
        p.exists().then(|| std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("read {RUNTIME_JS}: {e}")))
    }

    /// TUWA4: every output on disk equals a fresh render. Never rewrites.
    #[test]
    fn generated_files_are_fresh() {
        let rt = runtime();
        let outs = render(catalog(), rt.as_deref()).unwrap_or_else(|e| panic!("{e}"));
        let mut stale = Vec::new();
        for o in &outs {
            let on_disk = if o.path == CLI {
                let cli = read(CLI);
                cli_block_in(&cli).unwrap_or_else(|e| panic!("{e}; {REGEN}")).to_string()
            } else {
                read(o.path)
            };
            if on_disk != o.text {
                stale.push(o.path);
            }
        }
        assert!(stale.is_empty(), "stale generated files {stale:?}: {REGEN}");
    }

    #[test]
    fn zen_verbs_is_todays_37_plus_nothing_else() {
        let rows = bridge_rows(catalog());
        assert_eq!(rows.len(), 37, "today's ZEN_VERBS has 37 entries");
        assert!(!rows.iter().any(|v| v.verb == "theme.changed"), "a frame row is never in ZEN_VERBS");
        let widget: Vec<&str> = catalog().verbs_exposed_to(Exposure::Widget).iter().map(|v| v.verb.as_str()).collect();
        assert_eq!(widget.len(), 16, "UW16 + UWB10: 16 widget verbs");
        for never in ["zen.exit", "controls.bind", "homes.list", "agents.local", "agents.add", "agents.home", "agents.setHome",
            "thread.void", "thread.markRead", "gardens.create", "gardens.rename", "gardens.delete", "app.open"]
        {
            assert!(!widget.contains(&never), "{never} is never a widget verb");
        }
    }

    #[test]
    fn frame_script_fits_its_budget() {
        let rt = runtime();
        let outs = render(catalog(), rt.as_deref()).expect("renders");
        let js = outs.iter().find(|o| o.path == K2_FRAME_JS).expect("frame output");
        assert!(js.text.len() <= FRAME_MAX_BYTES, "k2-frame.js is {} bytes (cap {FRAME_MAX_BYTES})", js.text.len());
        assert!(js.text.contains("K2_CONTRACT"), "the runtime reads K2_CONTRACT");
    }

    #[test]
    fn guide_api_page_is_short_and_complete() {
        let page = guide_api_page(catalog());
        let n = page.lines().count();
        assert!(n <= GUIDE_MAX_LINES, "guide api is {n} lines (max {GUIDE_MAX_LINES})");
        assert!(page.starts_with("k2 zen guide api —"));
        for v in catalog().verbs_exposed_to(Exposure::Widget) {
            let line = page
                .lines()
                .find(|l| l.starts_with(&format!("  k2.{} ", signature(v))))
                .unwrap_or_else(|| panic!("guide api has no line for {}", v.verb));
            assert!(line.contains(reach_name(v)) && line.contains(&v.feature), "{line}");
        }
        for cap in catalog().caps_exposed_to(Exposure::Widget) {
            assert!(page.lines().any(|l| l.starts_with(cap)), "guide api groups {cap}");
        }
    }

    #[test]
    fn guide_examples_use_only_real_helpers() {
        let widget: Vec<String> = catalog().verbs_exposed_to(Exposure::Widget).iter().map(|v| v.verb.clone()).collect();
        let mut seen = 0;
        for e in GUIDE_EXAMPLES {
            for (i, _) in e.match_indices("k2.") {
                let rest = &e[i + 3..];
                let name: String = rest.chars().take_while(|ch| ch.is_ascii_alphanumeric() || *ch == '.').collect();
                let name = name.trim_end_matches('.');
                let ok = widget.iter().any(|w| w == name) || RUNTIME_MEMBERS.contains(&name);
                assert!(ok, "guide example uses k2.{name}, which isn't a widget helper: {e}");
                seen += 1;
            }
            // k2.can('verb') names a real verb.
            if let Some(i) = e.find("k2.can('") {
                let v: String = e[i + 8..].chars().take_while(|ch| *ch != '\'').collect();
                assert!(widget.contains(&v), "{e}");
            }
        }
        assert_eq!(GUIDE_EXAMPLES.len(), 10);
        // Nine use k2; one shows the textContent rule.
        assert!(seen >= 9, "{seen}");
    }

    #[test]
    fn signatures_read_like_the_skill() {
        let c = catalog();
        let sig = |v: &str| signature(c.verb(v).unwrap_or_else(|| panic!("{v}")));
        assert_eq!(sig("thread.read"), "thread.read(address, {beforeSeq, limit})");
        assert_eq!(sig("agents.subscribe"), "agents.subscribe(cb)");
        assert_eq!(sig("thread.subscribe"), "thread.subscribe(address, cb)");
        assert_eq!(sig("controls.bind"), "controls.bind(kind, element, gardenId?)");
        assert_eq!(sig("theme.changed"), "theme.changed(cb)");
        assert_eq!(sig("zen.exit"), "zen.exit()");
    }

    #[test]
    fn splice_replaces_only_the_block() {
        let cli = format!("before\n{CLI_BEGIN} (x)\nold\n{CLI_END}\nafter\n");
        let got = splice_cli(&cli, &format!("{CLI_BEGIN} (y)\nnew\n{CLI_END}\n")).expect("splices");
        assert_eq!(got, format!("before\n{CLI_BEGIN} (y)\nnew\n{CLI_END}\nafter\n"));
        assert!(splice_cli("no markers\n", "x").is_err());
    }

    #[test]
    fn exposed_types_never_name_a_banned_field() {
        let dts = k2_dts(catalog()).expect("d.ts renders");
        for b in &catalog().banned_fields {
            assert!(!dts.contains(&format!(" {b}:")) && !dts.contains(&format!(" {b}?:")), "k2.d.ts names banned field {b}");
        }
    }

    /// Integrator decision (B4 Q2): a refused subscription answers
    /// `{sub, error}`; every subscribe helper takes an `onError` after `cb`.
    #[test]
    fn subscribe_helpers_take_on_error() {
        let dts = k2_dts(catalog()).expect("d.ts renders");
        let subs: Vec<&str> = dts.lines().filter(|l| l.contains("cb: (value:")).collect();
        assert!(!subs.is_empty(), "k2.d.ts has subscribe helpers");
        for l in subs {
            assert!(l.contains("onError?: (error: K2Error) => void"), "subscribe helper without onError: {l}");
        }
        assert!(dts.contains("(value: K2Verbs[V]['value']) => void, (error: K2Error) => void]"));
    }
}
