// The generated contract files (prd-zen-user-widgets-v2 UWA4, UWA9, TUWA4,
// TUWA5, TUWA10, UWB28).
//
// The Rust freshness test (`k2_core::contract::gen`) renders every output
// again, but CI runs only `cargo check` until the contract step lands
// everywhere, so this vitest twin checks the same thing from the other side:
// `contract-snapshot.json` (written by contract-gen) records the sha256 of
// the catalog, the runtime and every output. A catalog edit without a
// regenerate, or a hand edit of a generated file, fails here.
import { createHash } from 'node:crypto'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { CATALOG_ERROR_CODES, type Catalog } from './catalog-types'
import { K2_CAPS, USER_WIDGET_CAPS } from '../k2-caps.generated'
import { ZEN_CATALOG_VERSION, ZEN_CUSTOM_VERBS, ZEN_VERBS } from '../zen/zen-verbs.generated'

const ROOT = resolve(__dirname, '../../../..')
const REGEN = 'run `cargo run -p k2-core --bin contract-gen`'

const sha = (text: string): string => createHash('sha256').update(text, 'utf8').digest('hex')
const read = (rel: string): string => readFileSync(resolve(ROOT, rel), 'utf8')

interface Snapshot {
  catalogVersion: number
  catalogSha256: string
  runtimeSha256: string | null
  files: Record<string, string>
}

const snapshot = JSON.parse(read('sdk/generated/contract-snapshot.json')) as Snapshot
const catalogText = read('crates/k2-core/src/contract/catalog.json')
const catalog = JSON.parse(catalogText) as Catalog

/** The fenced block in cli/k2, markers included (as contract-gen splices it). */
function cliBlock(cli: string): string {
  const begin = cli.indexOf('# >>> generated by contract-gen: zen guide api')
  expect(begin, `cli/k2 has no generated guide block; ${REGEN}`).toBeGreaterThanOrEqual(0)
  const rest = cli.slice(begin)
  const end = rest.indexOf('# <<< generated')
  expect(end, 'cli/k2 block has no end marker').toBeGreaterThan(0)
  const nl = rest.indexOf('\n', end)
  return rest.slice(0, nl === -1 ? rest.length : nl + 1)
}

describe('TUWA4 twin: generated files match the catalog', () => {
  it('the snapshot was written from this catalog', () => {
    expect(sha(catalogText), `catalog.json changed since the last generate; ${REGEN}`).toBe(snapshot.catalogSha256)
    expect(snapshot.catalogVersion).toBe(catalog.catalogVersion)
    expect(ZEN_CATALOG_VERSION).toBe(catalog.catalogVersion)
  })

  it('the runtime the frame script joined is the one on disk', () => {
    const p = resolve(ROOT, 'sdk/k2-runtime.js')
    const now = existsSync(p) ? sha(readFileSync(p, 'utf8')) : null
    expect(now, `sdk/k2-runtime.js changed since the last generate; ${REGEN}`).toBe(snapshot.runtimeSha256)
  })

  it('every output is as generated', () => {
    const paths = Object.keys(snapshot.files).sort()
    expect(paths).toEqual(
      [
        'cli/k2',
        'sdk/generated/k2-frame.js',
        'sdk/generated/k2.d.ts',
        'src/renderer/lib/k2-caps.generated.ts',
        'src/renderer/lib/zen/zen-verbs.generated.ts',
      ].sort(),
    )
    for (const rel of paths) {
      const text = rel === 'cli/k2' ? cliBlock(read(rel)) : read(rel)
      expect(sha(text), `${rel} differs from what contract-gen wrote; ${REGEN}`).toBe(snapshot.files[rel])
    }
  })

  it('the frame script stays under 16 KB (UWA5)', () => {
    expect(Buffer.byteLength(read('sdk/generated/k2-frame.js'), 'utf8')).toBeLessThanOrEqual(16 * 1024)
  })
})

describe('TUWA5: the generated tables', () => {
  it('ZEN_VERBS is today’s 37 entries, key for key and cap for cap', () => {
    expect(ZEN_VERBS).toEqual({
      'agents.list': 'agents:read',
      'agents.subscribe': 'agents:read',
      'agents.add': 'agents:add',
      'agents.home': 'agents:read',
      'agents.setHome': 'agents:read',
      'agents.local': 'agents:read',
      'presence.get': 'presence:read',
      'presence.subscribe': 'presence:read',
      'conversation.open': 'agents:read',
      'conversation.close': 'agents:read',
      'thread.read': 'thread:read',
      'thread.subscribe': 'thread:read',
      'thread.markRead': 'thread:read',
      'thread.post': 'thread:post',
      'thread.answer': 'thread:post',
      'thread.void': 'thread:post',
      'compose.draft': 'thread:post',
      'focusGroups.get': 'agents:read',
      'focusGroups.set': 'agents:read',
      'focusGroups.subscribe': 'agents:read',
      'app.open': 'app:navigate',
      'app.current': 'app:navigate',
      'app.subscribeCurrent': 'app:navigate',
      'app.badges': 'app:navigate',
      'app.subscribe': 'app:navigate',
      'homes.list': 'agents:read',
      'gardens.list': null,
      'gardens.current': null,
      'gardens.switch': null,
      'gardens.create': 'gardens:manage',
      'gardens.rename': 'gardens:manage',
      'gardens.delete': 'gardens:manage',
      'gardens.empty': 'gardens:template',
      'gardens.useTemplate': 'gardens:template',
      'zen.exit': null,
      'controls.bind': null,
      'theme.get': null,
    })
    expect(Object.keys(ZEN_VERBS)).toHaveLength(37)
  })

  it('ZEN_CUSTOM_VERBS is the UW16 list as amended by UWB10, plus the whole canvas (0.45.3)', () => {
    expect(ZEN_CUSTOM_VERBS).toEqual({
      'gardens.list': { cap: null, reach: 'local', kind: 'call' },
      'gardens.current': { cap: null, reach: 'local', kind: 'call' },
      'gardens.switch': { cap: null, reach: 'local', kind: 'call' },
      'theme.get': { cap: null, reach: 'local', kind: 'call' },
      'theme.changed': { cap: null, reach: 'local', kind: 'event' },
      'canvas.setHitRegions': { cap: null, reach: 'local', kind: 'call' },
      'window.startDrag': { cap: null, reach: 'local', kind: 'call' },
      'agents.list': { cap: 'agents:read', reach: 'portable', kind: 'call' },
      'agents.subscribe': { cap: 'agents:read', reach: 'portable', kind: 'subscribe' },
      'conversation.open': { cap: 'agents:read', reach: 'local', kind: 'call' },
      'conversation.close': { cap: 'agents:read', reach: 'local', kind: 'call' },
      'presence.get': { cap: 'presence:read', reach: 'local', kind: 'call' },
      'presence.subscribe': { cap: 'presence:read', reach: 'local', kind: 'subscribe' },
      'thread.read': { cap: 'thread:read', reach: 'portable', kind: 'call' },
      'thread.subscribe': { cap: 'thread:read', reach: 'portable', kind: 'subscribe' },
      'thread.post': { cap: 'thread:post', reach: 'portable', kind: 'call' },
      'thread.answer': { cap: 'thread:post', reach: 'portable', kind: 'call' },
      'compose.draft': { cap: 'thread:post', reach: 'local', kind: 'call' },
    })
  })

  it('widget caps are bridge caps, and K2’s own caps never are widget caps (UW69)', () => {
    const bridgeCaps = new Set(Object.values(ZEN_VERBS).filter((c): c is NonNullable<typeof c> => c !== null))
    for (const c of USER_WIDGET_CAPS) expect(bridgeCaps.has(c), c).toBe(true)
    for (const c of ['gardens:manage', 'gardens:template', 'agents:add', 'app:navigate']) {
      expect((USER_WIDGET_CAPS as readonly string[]).includes(c), c).toBe(false)
    }
  })

  it('every custom verb’s cap is a widget cap, and the error list is the catalog’s', () => {
    for (const [verb, row] of Object.entries(ZEN_CUSTOM_VERBS)) {
      if (row.cap !== null) expect(USER_WIDGET_CAPS as readonly string[], verb).toContain(row.cap)
    }
    expect(catalog.errors.map((e) => e.code)).toEqual([...CATALOG_ERROR_CODES])
  })
})

describe('TUWA10: one cap table', () => {
  it('app caps keep today’s Settings → Apps words', () => {
    const app = Object.fromEntries(
      Object.entries(K2_CAPS)
        .filter(([, v]) => (v.exposure as readonly string[]).includes('app'))
        .map(([k, v]) => [k, v.label]),
    )
    expect(app).toEqual({
      'thread:read': 'Read the Thread',
      'thread:post': 'Post to the Thread',
      'files:read': 'Read files (also shows heartbeat instructions)',
      'files:write': 'Write files (not .k2/heartbeats)',
      'tickets:read': 'Read tickets and get live ticket updates',
      'tickets:post': 'Open, answer, assign and set status on tickets',
      'wiki:read': 'Read the wiki',
      'store:read': 'Read the workspace store',
      'store:write': 'Change dump-table rows',
      'activity:read': 'See when the agent is working',
      'heartbeats:read': 'See heartbeats: schedule, next fire, history',
      'heartbeats:write': 'Add, edit, turn on or off, archive and fire heartbeats',
    })
  })

  it('every widget cap has K2’s sentence for the review dialog', () => {
    for (const c of USER_WIDGET_CAPS) {
      const info = K2_CAPS[c]
      expect('sentence' in info && typeof info.sentence === 'string' && info.sentence.length > 0, c).toBe(true)
    }
  })
})
