// AUTO-GENERATED from VS Code theme-seti (Seti UI / jesseweed). MIT.
// Includes dark + light glyph colors. Do not hand-edit.

export interface SetiIconDef { code: number; color: string }

export const SETI_ICON_DEFS: Record<string, SetiIconDef> = {
  "_R": { code: 57345, color: "#519aba" },
  "_argdown": { code: 57347, color: "#519aba" },
  "_asm": { code: 57348, color: "#cc3e44" },
  "_audio": { code: 57349, color: "#a074c4" },
  "_babel": { code: 57350, color: "#cbcb41" },
  "_bazel": { code: 57351, color: "#8dc149" },
  "_bazel_1": { code: 57351, color: "#4d5a5e" },
  "_bicep": { code: 57352, color: "#519aba" },
  "_bower": { code: 57353, color: "#e37933" },
  "_bsl": { code: 57354, color: "#cc3e44" },
  "_c": { code: 57356, color: "#519aba" },
  "_c-sharp": { code: 57355, color: "#519aba" },
  "_c_1": { code: 57356, color: "#a074c4" },
  "_c_2": { code: 57356, color: "#cbcb41" },
  "_cake": { code: 57357, color: "#cc3e44" },
  "_cake_php": { code: 57358, color: "#cc3e44" },
  "_clock": { code: 57362, color: "#519aba" },
  "_clock_1": { code: 57362, color: "#6d8086" },
  "_clojure": { code: 57363, color: "#8dc149" },
  "_clojure_1": { code: 57363, color: "#519aba" },
  "_code-climate": { code: 57364, color: "#8dc149" },
  "_code-search": { code: 57365, color: "#a074c4" },
  "_coffee": { code: 57366, color: "#cbcb41" },
  "_coldfusion": { code: 57368, color: "#519aba" },
  "_config": { code: 57369, color: "#6d8086" },
  "_cpp": { code: 57370, color: "#519aba" },
  "_cpp_1": { code: 57370, color: "#a074c4" },
  "_cpp_2": { code: 57370, color: "#cbcb41" },
  "_crystal": { code: 57371, color: "#d4d7d6" },
  "_crystal_embedded": { code: 57372, color: "#d4d7d6" },
  "_css": { code: 57373, color: "#519aba" },
  "_csv": { code: 57374, color: "#8dc149" },
  "_cu": { code: 57375, color: "#8dc149" },
  "_cu_1": { code: 57375, color: "#a074c4" },
  "_d": { code: 57376, color: "#cc3e44" },
  "_dart": { code: 57377, color: "#519aba" },
  "_db": { code: 57378, color: "#f55385" },
  "_db_1": { code: 57378, color: "#519aba" },
  "_default": { code: 57379, color: "#d4d7d6" },
  "_docker": { code: 57381, color: "#519aba" },
  "_docker_1": { code: 57381, color: "#4d5a5e" },
  "_docker_2": { code: 57381, color: "#8dc149" },
  "_docker_3": { code: 57381, color: "#f55385" },
  "_ejs": { code: 57383, color: "#cbcb41" },
  "_elixir": { code: 57384, color: "#a074c4" },
  "_elixir_script": { code: 57385, color: "#a074c4" },
  "_elm": { code: 57386, color: "#519aba" },
  "_eslint": { code: 57388, color: "#a074c4" },
  "_eslint_1": { code: 57388, color: "#4d5a5e" },
  "_ethereum": { code: 57389, color: "#519aba" },
  "_f-sharp": { code: 57390, color: "#519aba" },
  "_favicon": { code: 57391, color: "#cbcb41" },
  "_firebase": { code: 57392, color: "#e37933" },
  "_firefox": { code: 57393, color: "#e37933" },
  "_font": { code: 57395, color: "#cc3e44" },
  "_git": { code: 57396, color: "#41535b" },
  "_github": { code: 57399, color: "#d4d7d6" },
  "_gitlab": { code: 57400, color: "#e37933" },
  "_go": { code: 57401, color: "#519aba" },
  "_go2": { code: 57402, color: "#519aba" },
  "_godot": { code: 57403, color: "#519aba" },
  "_godot_1": { code: 57403, color: "#cc3e44" },
  "_godot_2": { code: 57403, color: "#cbcb41" },
  "_godot_3": { code: 57403, color: "#a074c4" },
  "_gradle": { code: 57404, color: "#519aba" },
  "_grails": { code: 57405, color: "#8dc149" },
  "_graphql": { code: 57406, color: "#f55385" },
  "_grunt": { code: 57407, color: "#e37933" },
  "_gulp": { code: 57408, color: "#cc3e44" },
  "_hacklang": { code: 57409, color: "#e37933" },
  "_haml": { code: 57410, color: "#cc3e44" },
  "_happenings": { code: 57411, color: "#519aba" },
  "_haskell": { code: 57412, color: "#a074c4" },
  "_haxe": { code: 57413, color: "#e37933" },
  "_haxe_1": { code: 57413, color: "#cbcb41" },
  "_haxe_2": { code: 57413, color: "#519aba" },
  "_haxe_3": { code: 57413, color: "#a074c4" },
  "_heroku": { code: 57414, color: "#a074c4" },
  "_hex": { code: 57415, color: "#cc3e44" },
  "_html": { code: 57416, color: "#519aba" },
  "_html_1": { code: 57416, color: "#8dc149" },
  "_html_2": { code: 57416, color: "#cbcb41" },
  "_html_3": { code: 57416, color: "#e37933" },
  "_html_erb": { code: 57417, color: "#cc3e44" },
  "_ignored": { code: 57418, color: "#41535b" },
  "_illustrator": { code: 57419, color: "#cbcb41" },
  "_image": { code: 57420, color: "#a074c4" },
  "_info": { code: 57421, color: "#519aba" },
  "_ionic": { code: 57422, color: "#519aba" },
  "_jade": { code: 57423, color: "#cc3e44" },
  "_java": { code: 57424, color: "#cc3e44" },
  "_java_1": { code: 57424, color: "#519aba" },
  "_javascript": { code: 57425, color: "#cbcb41" },
  "_javascript_1": { code: 57425, color: "#e37933" },
  "_javascript_2": { code: 57425, color: "#519aba" },
  "_jenkins": { code: 57426, color: "#cc3e44" },
  "_jinja": { code: 57427, color: "#cc3e44" },
  "_json": { code: 57429, color: "#cbcb41" },
  "_json_1": { code: 57429, color: "#8dc149" },
  "_julia": { code: 57430, color: "#a074c4" },
  "_karma": { code: 57431, color: "#8dc149" },
  "_kotlin": { code: 57432, color: "#e37933" },
  "_less": { code: 57433, color: "#519aba" },
  "_license": { code: 57434, color: "#cbcb41" },
  "_license_1": { code: 57434, color: "#e37933" },
  "_license_2": { code: 57434, color: "#cc3e44" },
  "_liquid": { code: 57435, color: "#8dc149" },
  "_livescript": { code: 57436, color: "#519aba" },
  "_lock": { code: 57437, color: "#8dc149" },
  "_lua": { code: 57438, color: "#519aba" },
  "_makefile": { code: 57439, color: "#e37933" },
  "_makefile_1": { code: 57439, color: "#a074c4" },
  "_makefile_2": { code: 57439, color: "#6d8086" },
  "_makefile_3": { code: 57439, color: "#519aba" },
  "_markdown": { code: 57440, color: "#519aba" },
  "_maven": { code: 57441, color: "#cc3e44" },
  "_mdo": { code: 57442, color: "#cc3e44" },
  "_mustache": { code: 57443, color: "#e37933" },
  "_nim": { code: 57445, color: "#cbcb41" },
  "_notebook": { code: 57446, color: "#519aba" },
  "_npm": { code: 57447, color: "#41535b" },
  "_npm_1": { code: 57447, color: "#cc3e44" },
  "_npm_ignored": { code: 57448, color: "#41535b" },
  "_nunjucks": { code: 57449, color: "#8dc149" },
  "_ocaml": { code: 57450, color: "#e37933" },
  "_odata": { code: 57451, color: "#e37933" },
  "_pddl": { code: 57452, color: "#a074c4" },
  "_pdf": { code: 57453, color: "#cc3e44" },
  "_perl": { code: 57454, color: "#519aba" },
  "_photoshop": { code: 57455, color: "#519aba" },
  "_php": { code: 57456, color: "#a074c4" },
  "_pipeline": { code: 57457, color: "#e37933" },
  "_plan": { code: 57458, color: "#8dc149" },
  "_platformio": { code: 57459, color: "#e37933" },
  "_powershell": { code: 57460, color: "#519aba" },
  "_prisma": { code: 57461, color: "#519aba" },
  "_prolog": { code: 57463, color: "#e37933" },
  "_pug": { code: 57464, color: "#cc3e44" },
  "_puppet": { code: 57465, color: "#cbcb41" },
  "_purescript": { code: 57466, color: "#d4d7d6" },
  "_python": { code: 57467, color: "#519aba" },
  "_react": { code: 57469, color: "#519aba" },
  "_react_1": { code: 57469, color: "#e37933" },
  "_reasonml": { code: 57470, color: "#cc3e44" },
  "_rescript": { code: 57471, color: "#cc3e44" },
  "_rescript_1": { code: 57471, color: "#f55385" },
  "_rollup": { code: 57472, color: "#cc3e44" },
  "_ruby": { code: 57473, color: "#cc3e44" },
  "_rust": { code: 57474, color: "#6d8086" },
  "_salesforce": { code: 57475, color: "#519aba" },
  "_sass": { code: 57476, color: "#f55385" },
  "_sbt": { code: 57477, color: "#519aba" },
  "_scala": { code: 57478, color: "#cc3e44" },
  "_shell": { code: 57481, color: "#8dc149" },
  "_slim": { code: 57482, color: "#e37933" },
  "_smarty": { code: 57483, color: "#cbcb41" },
  "_spring": { code: 57484, color: "#8dc149" },
  "_stylelint": { code: 57485, color: "#d4d7d6" },
  "_stylelint_1": { code: 57485, color: "#4d5a5e" },
  "_stylus": { code: 57486, color: "#8dc149" },
  "_sublime": { code: 57487, color: "#e37933" },
  "_svelte": { code: 57488, color: "#cc3e44" },
  "_svg": { code: 57489, color: "#a074c4" },
  "_svg_1": { code: 57489, color: "#519aba" },
  "_swift": { code: 57490, color: "#e37933" },
  "_terraform": { code: 57491, color: "#a074c4" },
  "_tex": { code: 57492, color: "#519aba" },
  "_tex_1": { code: 57492, color: "#cbcb41" },
  "_tex_2": { code: 57492, color: "#e37933" },
  "_tex_3": { code: 57492, color: "#d4d7d6" },
  "_todo": { code: 57494, color: "#d4d7d6" },
  "_tsconfig": { code: 57495, color: "#519aba" },
  "_twig": { code: 57496, color: "#8dc149" },
  "_typescript": { code: 57497, color: "#519aba" },
  "_typescript_1": { code: 57497, color: "#e37933" },
  "_vala": { code: 57498, color: "#6d8086" },
  "_video": { code: 57499, color: "#f55385" },
  "_vite": { code: 57500, color: "#cbcb41" },
  "_vue": { code: 57501, color: "#8dc149" },
  "_wasm": { code: 57502, color: "#a074c4" },
  "_wat": { code: 57503, color: "#a074c4" },
  "_webpack": { code: 57504, color: "#519aba" },
  "_wgt": { code: 57505, color: "#519aba" },
  "_windows": { code: 57506, color: "#519aba" },
  "_word": { code: 57507, color: "#519aba" },
  "_xls": { code: 57508, color: "#8dc149" },
  "_xml": { code: 57509, color: "#e37933" },
  "_yarn": { code: 57510, color: "#519aba" },
  "_yml": { code: 57511, color: "#a074c4" },
  "_zig": { code: 57512, color: "#e37933" },
  "_zip": { code: 57513, color: "#cc3e44" },
  "_zip_1": { code: 57513, color: "#6d8086" },
  "_R_light": { code: 57345, color: "#498ba7" },
  "_argdown_light": { code: 57347, color: "#498ba7" },
  "_asm_light": { code: 57348, color: "#b8383d" },
  "_audio_light": { code: 57349, color: "#9068b0" },
  "_babel_light": { code: 57350, color: "#b7b73b" },
  "_bazel_1_light": { code: 57351, color: "#455155" },
  "_bazel_light": { code: 57351, color: "#7fae42" },
  "_bicep_light": { code: 57352, color: "#498ba7" },
  "_bower_light": { code: 57353, color: "#cc6d2e" },
  "_bsl_light": { code: 57354, color: "#b8383d" },
  "_c-sharp_light": { code: 57355, color: "#498ba7" },
  "_c_1_light": { code: 57356, color: "#9068b0" },
  "_c_2_light": { code: 57356, color: "#b7b73b" },
  "_c_light": { code: 57356, color: "#498ba7" },
  "_cake_light": { code: 57357, color: "#b8383d" },
  "_cake_php_light": { code: 57358, color: "#b8383d" },
  "_clock_1_light": { code: 57362, color: "#627379" },
  "_clock_light": { code: 57362, color: "#498ba7" },
  "_clojure_1_light": { code: 57363, color: "#498ba7" },
  "_clojure_light": { code: 57363, color: "#7fae42" },
  "_code-climate_light": { code: 57364, color: "#7fae42" },
  "_code-search_light": { code: 57365, color: "#9068b0" },
  "_coffee_light": { code: 57366, color: "#b7b73b" },
  "_coldfusion_light": { code: 57368, color: "#498ba7" },
  "_config_light": { code: 57369, color: "#627379" },
  "_cpp_1_light": { code: 57370, color: "#9068b0" },
  "_cpp_2_light": { code: 57370, color: "#b7b73b" },
  "_cpp_light": { code: 57370, color: "#498ba7" },
  "_crystal_embedded_light": { code: 57372, color: "#bfc2c1" },
  "_crystal_light": { code: 57371, color: "#bfc2c1" },
  "_css_light": { code: 57373, color: "#498ba7" },
  "_csv_light": { code: 57374, color: "#7fae42" },
  "_cu_1_light": { code: 57375, color: "#9068b0" },
  "_cu_light": { code: 57375, color: "#7fae42" },
  "_d_light": { code: 57376, color: "#b8383d" },
  "_dart_light": { code: 57377, color: "#498ba7" },
  "_db_1_light": { code: 57378, color: "#498ba7" },
  "_db_light": { code: 57378, color: "#dd4b78" },
  "_default_light": { code: 57379, color: "#bfc2c1" },
  "_docker_1_light": { code: 57381, color: "#455155" },
  "_docker_2_light": { code: 57381, color: "#7fae42" },
  "_docker_3_light": { code: 57381, color: "#dd4b78" },
  "_docker_light": { code: 57381, color: "#498ba7" },
  "_ejs_light": { code: 57383, color: "#b7b73b" },
  "_elixir_light": { code: 57384, color: "#9068b0" },
  "_elixir_script_light": { code: 57385, color: "#9068b0" },
  "_elm_light": { code: 57386, color: "#498ba7" },
  "_eslint_1_light": { code: 57388, color: "#455155" },
  "_eslint_light": { code: 57388, color: "#9068b0" },
  "_ethereum_light": { code: 57389, color: "#498ba7" },
  "_f-sharp_light": { code: 57390, color: "#498ba7" },
  "_favicon_light": { code: 57391, color: "#b7b73b" },
  "_firebase_light": { code: 57392, color: "#cc6d2e" },
  "_firefox_light": { code: 57393, color: "#cc6d2e" },
  "_font_light": { code: 57395, color: "#b8383d" },
  "_git_light": { code: 57396, color: "#3b4b52" },
  "_github_light": { code: 57399, color: "#bfc2c1" },
  "_gitlab_light": { code: 57400, color: "#cc6d2e" },
  "_go2_light": { code: 57402, color: "#498ba7" },
  "_go_light": { code: 57401, color: "#498ba7" },
  "_godot_1_light": { code: 57403, color: "#b8383d" },
  "_godot_2_light": { code: 57403, color: "#b7b73b" },
  "_godot_3_light": { code: 57403, color: "#9068b0" },
  "_godot_light": { code: 57403, color: "#498ba7" },
  "_gradle_light": { code: 57404, color: "#498ba7" },
  "_grails_light": { code: 57405, color: "#7fae42" },
  "_graphql_light": { code: 57406, color: "#dd4b78" },
  "_grunt_light": { code: 57407, color: "#cc6d2e" },
  "_gulp_light": { code: 57408, color: "#b8383d" },
  "_hacklang_light": { code: 57409, color: "#cc6d2e" },
  "_haml_light": { code: 57410, color: "#b8383d" },
  "_happenings_light": { code: 57411, color: "#498ba7" },
  "_haskell_light": { code: 57412, color: "#9068b0" },
  "_haxe_1_light": { code: 57413, color: "#b7b73b" },
  "_haxe_2_light": { code: 57413, color: "#498ba7" },
  "_haxe_3_light": { code: 57413, color: "#9068b0" },
  "_haxe_light": { code: 57413, color: "#cc6d2e" },
  "_heroku_light": { code: 57414, color: "#9068b0" },
  "_hex_light": { code: 57415, color: "#b8383d" },
  "_html_1_light": { code: 57416, color: "#7fae42" },
  "_html_2_light": { code: 57416, color: "#b7b73b" },
  "_html_3_light": { code: 57416, color: "#cc6d2e" },
  "_html_erb_light": { code: 57417, color: "#b8383d" },
  "_html_light": { code: 57416, color: "#498ba7" },
  "_ignored_light": { code: 57418, color: "#3b4b52" },
  "_illustrator_light": { code: 57419, color: "#b7b73b" },
  "_image_light": { code: 57420, color: "#9068b0" },
  "_info_light": { code: 57421, color: "#498ba7" },
  "_ionic_light": { code: 57422, color: "#498ba7" },
  "_jade_light": { code: 57423, color: "#b8383d" },
  "_java_1_light": { code: 57424, color: "#498ba7" },
  "_java_light": { code: 57424, color: "#b8383d" },
  "_javascript_1_light": { code: 57425, color: "#cc6d2e" },
  "_javascript_2_light": { code: 57425, color: "#498ba7" },
  "_javascript_light": { code: 57425, color: "#b7b73b" },
  "_jenkins_light": { code: 57426, color: "#b8383d" },
  "_jinja_light": { code: 57427, color: "#b8383d" },
  "_json_1_light": { code: 57429, color: "#7fae42" },
  "_json_light": { code: 57429, color: "#b7b73b" },
  "_julia_light": { code: 57430, color: "#9068b0" },
  "_karma_light": { code: 57431, color: "#7fae42" },
  "_kotlin_light": { code: 57432, color: "#cc6d2e" },
  "_less_light": { code: 57433, color: "#498ba7" },
  "_license_1_light": { code: 57434, color: "#cc6d2e" },
  "_license_2_light": { code: 57434, color: "#b8383d" },
  "_license_light": { code: 57434, color: "#b7b73b" },
  "_liquid_light": { code: 57435, color: "#7fae42" },
  "_livescript_light": { code: 57436, color: "#498ba7" },
  "_lock_light": { code: 57437, color: "#7fae42" },
  "_lua_light": { code: 57438, color: "#498ba7" },
  "_makefile_1_light": { code: 57439, color: "#9068b0" },
  "_makefile_2_light": { code: 57439, color: "#627379" },
  "_makefile_3_light": { code: 57439, color: "#498ba7" },
  "_makefile_light": { code: 57439, color: "#cc6d2e" },
  "_markdown_light": { code: 57440, color: "#498ba7" },
  "_maven_light": { code: 57441, color: "#b8383d" },
  "_mdo_light": { code: 57442, color: "#b8383d" },
  "_mustache_light": { code: 57443, color: "#cc6d2e" },
  "_nim_light": { code: 57445, color: "#b7b73b" },
  "_notebook_light": { code: 57446, color: "#498ba7" },
  "_npm_1_light": { code: 57447, color: "#b8383d" },
  "_npm_ignored_light": { code: 57448, color: "#3b4b52" },
  "_npm_light": { code: 57447, color: "#3b4b52" },
  "_nunjucks_light": { code: 57449, color: "#7fae42" },
  "_ocaml_light": { code: 57450, color: "#cc6d2e" },
  "_odata_light": { code: 57451, color: "#cc6d2e" },
  "_pddl_light": { code: 57452, color: "#9068b0" },
  "_pdf_light": { code: 57453, color: "#b8383d" },
  "_perl_light": { code: 57454, color: "#498ba7" },
  "_photoshop_light": { code: 57455, color: "#498ba7" },
  "_php_light": { code: 57456, color: "#9068b0" },
  "_pipeline_light": { code: 57457, color: "#cc6d2e" },
  "_plan_light": { code: 57458, color: "#7fae42" },
  "_platformio_light": { code: 57459, color: "#cc6d2e" },
  "_powershell_light": { code: 57460, color: "#498ba7" },
  "_prisma_light": { code: 57461, color: "#498ba7" },
  "_prolog_light": { code: 57463, color: "#cc6d2e" },
  "_pug_light": { code: 57464, color: "#b8383d" },
  "_puppet_light": { code: 57465, color: "#b7b73b" },
  "_purescript_light": { code: 57466, color: "#bfc2c1" },
  "_python_light": { code: 57467, color: "#498ba7" },
  "_react_1_light": { code: 57469, color: "#cc6d2e" },
  "_react_light": { code: 57469, color: "#498ba7" },
  "_reasonml_light": { code: 57470, color: "#b8383d" },
  "_rescript_1_light": { code: 57471, color: "#dd4b78" },
  "_rescript_light": { code: 57471, color: "#b8383d" },
  "_rollup_light": { code: 57472, color: "#b8383d" },
  "_ruby_light": { code: 57473, color: "#b8383d" },
  "_rust_light": { code: 57474, color: "#627379" },
  "_salesforce_light": { code: 57475, color: "#498ba7" },
  "_sass_light": { code: 57476, color: "#dd4b78" },
  "_sbt_light": { code: 57477, color: "#498ba7" },
  "_scala_light": { code: 57478, color: "#b8383d" },
  "_shell_light": { code: 57481, color: "#7fae42" },
  "_slim_light": { code: 57482, color: "#cc6d2e" },
  "_smarty_light": { code: 57483, color: "#b7b73b" },
  "_spring_light": { code: 57484, color: "#7fae42" },
  "_stylelint_1_light": { code: 57485, color: "#455155" },
  "_stylelint_light": { code: 57485, color: "#bfc2c1" },
  "_stylus_light": { code: 57486, color: "#7fae42" },
  "_sublime_light": { code: 57487, color: "#cc6d2e" },
  "_svelte_light": { code: 57488, color: "#b8383d" },
  "_svg_1_light": { code: 57489, color: "#498ba7" },
  "_svg_light": { code: 57489, color: "#9068b0" },
  "_swift_light": { code: 57490, color: "#cc6d2e" },
  "_terraform_light": { code: 57491, color: "#9068b0" },
  "_tex_1_light": { code: 57492, color: "#b7b73b" },
  "_tex_2_light": { code: 57492, color: "#cc6d2e" },
  "_tex_3_light": { code: 57492, color: "#bfc2c1" },
  "_tex_light": { code: 57492, color: "#498ba7" },
  "_tsconfig_light": { code: 57495, color: "#498ba7" },
  "_twig_light": { code: 57496, color: "#7fae42" },
  "_typescript_1_light": { code: 57497, color: "#cc6d2e" },
  "_typescript_light": { code: 57497, color: "#498ba7" },
  "_vala_light": { code: 57498, color: "#627379" },
  "_video_light": { code: 57499, color: "#dd4b78" },
  "_vite_light": { code: 57500, color: "#b7b73b" },
  "_vue_light": { code: 57501, color: "#7fae42" },
  "_wasm_light": { code: 57502, color: "#9068b0" },
  "_wat_light": { code: 57503, color: "#9068b0" },
  "_webpack_light": { code: 57504, color: "#498ba7" },
  "_wgt_light": { code: 57505, color: "#498ba7" },
  "_windows_light": { code: 57506, color: "#498ba7" },
  "_word_light": { code: 57507, color: "#498ba7" },
  "_xls_light": { code: 57508, color: "#7fae42" },
  "_xml_light": { code: 57509, color: "#cc6d2e" },
  "_yarn_light": { code: 57510, color: "#498ba7" },
  "_yml_light": { code: 57511, color: "#9068b0" },
  "_zig_light": { code: 57512, color: "#cc6d2e" },
  "_zip_1_light": { code: 57513, color: "#627379" },
  "_zip_light": { code: 57513, color: "#b8383d" },
}

export const SETI_FILE_EXTENSIONS: Record<string, string> = {
  "3dm": "_svg_1",
  "3ds": "_svg_1",
  "ad": "_argdown",
  "ai": "_illustrator",
  "apex": "_salesforce",
  "argdown": "_argdown",
  "article": "_go",
  "asax": "_html_2",
  "ascx": "_html_1",
  "asm": "_asm",
  "aspx": "_html",
  "avi": "_video",
  "avif": "_image",
  "babelrc": "_babel",
  "babelrc.cjs": "_babel",
  "babelrc.js": "_babel",
  "bash": "_shell",
  "bat": "_windows",
  "bazel": "_bazel",
  "bazelignore": "_bazel",
  "bazelrc": "_bazel_1",
  "bazelversion": "_bazel",
  "bicep": "_bicep",
  "bowerrc": "_bower",
  "bsl": "_bsl",
  "build": "_bazel",
  "bzl": "_bazel",
  "c": "_c",
  "cake": "_cake",
  "cc": "_cpp",
  "cer": "_lock",
  "cert": "_lock",
  "cfc": "_coldfusion",
  "cfm": "_coldfusion",
  "cjs": "_javascript",
  "cjs.map": "_javascript",
  "cjsx": "_react",
  "class": "_java_1",
  "classpath": "_java",
  "clj": "_clojure",
  "cljc": "_clojure",
  "cljs": "_clojure",
  "cls": "_salesforce",
  "cmd": "_windows",
  "cmx": "_ocaml",
  "cmxa": "_ocaml",
  "codeclimate.yml": "_code-climate",
  "coffee": "_coffee",
  "component": "_html_3",
  "config": "_config",
  "cpp": "_cpp",
  "cr": "_crystal",
  "crt": "_lock",
  "cs": "_c-sharp",
  "cson": "_json",
  "css": "_css",
  "css.map": "_css",
  "csv": "_csv",
  "ctp": "_cake_php",
  "cts": "_typescript",
  "cuh": "_cu_1",
  "cxx": "_cpp",
  "d": "_d",
  "dae": "_svg_1",
  "dart": "_dart",
  "direnv": "_config",
  "doc": "_word",
  "dockerfile": "_docker",
  "dockerignore": "_docker_1",
  "docx": "_word",
  "ds_store": "_ignored",
  "dtx": "_tex_2",
  "ecr": "_crystal_embedded",
  "edn": "_clojure_1",
  "ejs": "_ejs",
  "elm": "_elm",
  "eot": "_font",
  "epp": "_puppet",
  "erb": "_html_erb",
  "erb.html": "_html_erb",
  "es": "_javascript",
  "es5": "_javascript",
  "es7": "_javascript",
  "eslintignore": "_eslint_1",
  "eslintrc": "_eslint",
  "eslintrc.cjs": "_eslint",
  "eslintrc.js": "_eslint",
  "eslintrc.json": "_eslint",
  "eslintrc.yaml": "_eslint",
  "eslintrc.yml": "_eslint",
  "ex": "_elixir",
  "exs": "_elixir_script",
  "firebaserc": "_firebase",
  "fish": "_shell",
  "flac": "_audio",
  "fs": "_f-sharp",
  "fsi": "_f-sharp",
  "fsx": "_f-sharp",
  "gd": "_godot",
  "gif": "_image",
  "gitattributes": "_git",
  "gitconfig": "_git",
  "github-issues": "_github",
  "gitkeep": "_git",
  "gitlab-ci.yml": "_gitlab",
  "gitmodules": "_git",
  "go": "_go2",
  "godot": "_godot_1",
  "gql": "_graphql",
  "gradle": "_gradle",
  "graphql": "_graphql",
  "graphqls": "_graphql",
  "groovy": "_grails",
  "gsp": "_grails",
  "gvy": "_grails",
  "h": "_c_1",
  "h++": "_cpp_1",
  "hack": "_hacklang",
  "haml": "_haml",
  "happenings": "_happenings",
  "hbs": "_mustache",
  "hh": "_cpp_1",
  "hpp": "_cpp_1",
  "hs": "_haskell",
  "htaccess": "_config",
  "htm": "_html_3",
  "html": "_html_3",
  "html.erb": "_html_erb",
  "hu": "_cu_1",
  "hx": "_haxe",
  "hxml": "_haxe_3",
  "hxp": "_haxe_2",
  "hxs": "_haxe_1",
  "hxx": "_cpp_1",
  "ico": "_favicon",
  "ins": "_tex_3",
  "ipynb": "_notebook",
  "jade": "_jade",
  "jar": "_zip",
  "java": "_java",
  "jinja": "_jinja",
  "jinja2": "_jinja",
  "jl": "_julia",
  "jpeg": "_image",
  "jpg": "_image",
  "js": "_javascript",
  "js.map": "_javascript",
  "jscsrc": "_javascript_2",
  "jshintrc": "_javascript_2",
  "json": "_json",
  "jsonc": "_json",
  "jsx": "_react",
  "key": "_lock",
  "kt": "_kotlin",
  "kts": "_kotlin",
  "less": "_less",
  "lhs": "_haskell",
  "liquid": "_liquid",
  "litcoffee": "_coffee",
  "ls": "_livescript",
  "lua": "_lua",
  "m": "_c_2",
  "markdown": "_markdown",
  "master": "_html_2",
  "md": "_markdown",
  "mdo": "_mdo",
  "mjs": "_javascript",
  "mjs.map": "_javascript",
  "mk": "_makefile",
  "ml": "_ocaml",
  "mli": "_ocaml",
  "mm": "_cpp_2",
  "mov": "_video",
  "mp3": "_audio",
  "mp4": "_video",
  "mpg": "_video",
  "mts": "_typescript",
  "mustache": "_mustache",
  "nim": "_nim",
  "nims": "_nim",
  "nj": "_nunjucks",
  "njk": "_nunjucks",
  "njs": "_nunjucks",
  "npm-debug.log": "_npm",
  "npmignore": "_npm_1",
  "npmrc": "_npm_1",
  "nunj": "_nunjucks",
  "nunjs": "_nunjucks",
  "nunjucks": "_nunjucks",
  "obj": "_svg_1",
  "odata": "_odata",
  "ogg": "_audio",
  "ogv": "_video",
  "otf": "_font",
  "pddl": "_pddl",
  "pdf": "_pdf",
  "pem": "_lock",
  "php": "_php",
  "php.inc": "_php",
  "pipeline": "_pipeline",
  "pl": "_perl",
  "plan": "_plan",
  "pm": "_perl",
  "png": "_image",
  "pp": "_puppet",
  "prisma": "_prisma",
  "pro": "_prolog",
  "ps1": "_powershell",
  "psd": "_photoshop",
  "psm1": "_powershell",
  "purs": "_purescript",
  "pxm": "_image",
  "py": "_python",
  "pyi": "_python",
  "pyw": "_python",
  "r": "_R",
  "rb": "_ruby",
  "re": "_reasonml",
  "res": "_rescript",
  "resi": "_rescript_1",
  "rmd": "_R",
  "rs": "_rust",
  "s": "_asm",
  "sass": "_sass",
  "sbt": "_sbt",
  "scala": "_scala",
  "scss": "_sass",
  "sh": "_shell",
  "slang": "_crystal_embedded",
  "slide": "_go",
  "slim": "_slim",
  "slugignore": "_config",
  "smarty.tpl": "_smarty",
  "sol": "_ethereum",
  "soql": "_db_1",
  "spec.cjs": "_javascript_1",
  "spec.js": "_javascript_1",
  "spec.jsx": "_react_1",
  "spec.mjs": "_javascript_1",
  "spec.ts": "_typescript_1",
  "spec.tsx": "_react_1",
  "springbeans": "_spring",
  "sql": "_db",
  "sss": "_css",
  "stache": "_mustache",
  "static": "_config",
  "stl": "_svg_1",
  "styl": "_stylus",
  "stylelintignore": "_stylelint_1",
  "stylelintrc": "_stylelint",
  "stylelintrc.js": "_stylelint",
  "stylelintrc.json": "_stylelint",
  "stylelintrc.yaml": "_stylelint",
  "stylelintrc.yml": "_stylelint",
  "sublime-project": "_sublime",
  "sublime-workspace": "_sublime",
  "svelte": "_svelte",
  "svg": "_svg",
  "svgx": "_image",
  "swift": "_swift",
  "test.cjs": "_javascript_1",
  "test.js": "_javascript_1",
  "test.jsx": "_react_1",
  "test.mjs": "_javascript_1",
  "test.ts": "_typescript_1",
  "test.tsx": "_react_1",
  "tf": "_terraform",
  "tf.json": "_terraform",
  "tfvars": "_terraform",
  "tfvars.json": "_terraform",
  "tiff": "_image",
  "tmp": "_clock_1",
  "toml": "_config",
  "tpl": "_smarty",
  "tres": "_godot_2",
  "ts": "_typescript",
  "tscn": "_godot_3",
  "tsx": "_react",
  "ttf": "_font",
  "twig": "_twig",
  "vala": "_vala",
  "vapi": "_vala",
  "vue": "_vue",
  "wasm": "_wasm",
  "wat": "_wat",
  "wav": "_audio",
  "webm": "_video",
  "webp": "_image",
  "wgt": "_wgt",
  "woff": "_font",
  "woff2": "_font",
  "workspace": "_bazel",
  "xls": "_xls",
  "xlsx": "_xls",
  "xml": "_xml",
  "yaml": "_yml",
  "yml": "_yml",
  "zig": "_zig",
  "zip": "_zip_1",
  "zsh": "_shell",
}

export const SETI_FILE_EXTENSIONS_LIGHT: Record<string, string> = {
  "3dm": "_svg_1_light",
  "3ds": "_svg_1_light",
  "ad": "_argdown_light",
  "ai": "_illustrator_light",
  "apex": "_salesforce_light",
  "argdown": "_argdown_light",
  "article": "_go_light",
  "asax": "_html_2_light",
  "ascx": "_html_1_light",
  "asm": "_asm_light",
  "aspx": "_html_light",
  "avi": "_video_light",
  "avif": "_image_light",
  "babelrc": "_babel_light",
  "babelrc.cjs": "_babel_light",
  "babelrc.js": "_babel_light",
  "bash": "_shell_light",
  "bat": "_windows_light",
  "bazel": "_bazel_light",
  "bazelignore": "_bazel_light",
  "bazelrc": "_bazel_1_light",
  "bazelversion": "_bazel_light",
  "bicep": "_bicep_light",
  "bowerrc": "_bower_light",
  "bsl": "_bsl_light",
  "build": "_bazel_light",
  "bzl": "_bazel_light",
  "c": "_c_light",
  "cake": "_cake_light",
  "cc": "_cpp_light",
  "cer": "_lock_light",
  "cert": "_lock_light",
  "cfc": "_coldfusion_light",
  "cfm": "_coldfusion_light",
  "cjs": "_javascript_light",
  "cjs.map": "_javascript_light",
  "cjsx": "_react_light",
  "class": "_java_1_light",
  "classpath": "_java_light",
  "clj": "_clojure_light",
  "cljc": "_clojure_light",
  "cljs": "_clojure_light",
  "cls": "_salesforce_light",
  "cmd": "_windows_light",
  "cmx": "_ocaml_light",
  "cmxa": "_ocaml_light",
  "codeclimate.yml": "_code-climate_light",
  "coffee": "_coffee_light",
  "component": "_html_3_light",
  "config": "_config_light",
  "cpp": "_cpp_light",
  "cr": "_crystal_light",
  "crt": "_lock_light",
  "cs": "_c-sharp_light",
  "cson": "_json_light",
  "css": "_css_light",
  "css.map": "_css_light",
  "csv": "_csv_light",
  "ctp": "_cake_php_light",
  "cts": "_typescript_light",
  "cuh": "_cu_1_light",
  "cxx": "_cpp_light",
  "d": "_d_light",
  "dae": "_svg_1_light",
  "dart": "_dart_light",
  "direnv": "_config_light",
  "doc": "_word_light",
  "dockerfile": "_docker_light",
  "dockerignore": "_docker_1_light",
  "docx": "_word_light",
  "ds_store": "_ignored_light",
  "dtx": "_tex_2_light",
  "ecr": "_crystal_embedded_light",
  "edn": "_clojure_1_light",
  "ejs": "_ejs_light",
  "elm": "_elm_light",
  "eot": "_font_light",
  "epp": "_puppet_light",
  "erb": "_html_erb_light",
  "erb.html": "_html_erb_light",
  "es": "_javascript_light",
  "es5": "_javascript_light",
  "es7": "_javascript_light",
  "eslintignore": "_eslint_1_light",
  "eslintrc": "_eslint_light",
  "eslintrc.cjs": "_eslint_light",
  "eslintrc.js": "_eslint_light",
  "eslintrc.json": "_eslint_light",
  "eslintrc.yaml": "_eslint_light",
  "eslintrc.yml": "_eslint_light",
  "ex": "_elixir_light",
  "exs": "_elixir_script_light",
  "firebaserc": "_firebase_light",
  "fish": "_shell_light",
  "flac": "_audio_light",
  "fs": "_f-sharp_light",
  "fsi": "_f-sharp_light",
  "fsx": "_f-sharp_light",
  "gd": "_godot_light",
  "gif": "_image_light",
  "gitattributes": "_git_light",
  "gitconfig": "_git_light",
  "github-issues": "_github_light",
  "gitkeep": "_git_light",
  "gitlab-ci.yml": "_gitlab_light",
  "gitmodules": "_git_light",
  "go": "_go2_light",
  "godot": "_godot_1_light",
  "gql": "_graphql_light",
  "gradle": "_gradle_light",
  "graphql": "_graphql_light",
  "graphqls": "_graphql_light",
  "groovy": "_grails_light",
  "gsp": "_grails_light",
  "gvy": "_grails_light",
  "h": "_c_1_light",
  "h++": "_cpp_1_light",
  "hack": "_hacklang_light",
  "haml": "_haml_light",
  "happenings": "_happenings_light",
  "hbs": "_mustache_light",
  "hh": "_cpp_1_light",
  "hpp": "_cpp_1_light",
  "hs": "_haskell_light",
  "htaccess": "_config_light",
  "htm": "_html_3_light",
  "html": "_html_3_light",
  "html.erb": "_html_erb_light",
  "hu": "_cu_1_light",
  "hx": "_haxe_light",
  "hxml": "_haxe_3_light",
  "hxp": "_haxe_2_light",
  "hxs": "_haxe_1_light",
  "hxx": "_cpp_1_light",
  "ico": "_favicon_light",
  "ins": "_tex_3_light",
  "ipynb": "_notebook_light",
  "jade": "_jade_light",
  "jar": "_zip_light",
  "java": "_java_light",
  "jinja": "_jinja_light",
  "jinja2": "_jinja_light",
  "jl": "_julia_light",
  "jpeg": "_image_light",
  "jpg": "_image_light",
  "js": "_javascript_light",
  "js.map": "_javascript_light",
  "jscsrc": "_javascript_2_light",
  "jshintrc": "_javascript_2_light",
  "json": "_json_light",
  "jsonc": "_json_light",
  "jsx": "_react_light",
  "key": "_lock_light",
  "kt": "_kotlin_light",
  "kts": "_kotlin_light",
  "less": "_less_light",
  "lhs": "_haskell_light",
  "liquid": "_liquid_light",
  "litcoffee": "_coffee_light",
  "ls": "_livescript_light",
  "lua": "_lua_light",
  "m": "_c_2_light",
  "markdown": "_markdown_light",
  "master": "_html_2_light",
  "md": "_markdown_light",
  "mdo": "_mdo_light",
  "mjs": "_javascript_light",
  "mjs.map": "_javascript_light",
  "mk": "_makefile_light",
  "ml": "_ocaml_light",
  "mli": "_ocaml_light",
  "mm": "_cpp_2_light",
  "mov": "_video_light",
  "mp3": "_audio_light",
  "mp4": "_video_light",
  "mpg": "_video_light",
  "mts": "_typescript_light",
  "mustache": "_mustache_light",
  "nim": "_nim_light",
  "nims": "_nim_light",
  "nj": "_nunjucks_light",
  "njk": "_nunjucks_light",
  "njs": "_nunjucks_light",
  "npm-debug.log": "_npm_light",
  "npmignore": "_npm_1_light",
  "npmrc": "_npm_1_light",
  "nunj": "_nunjucks_light",
  "nunjs": "_nunjucks_light",
  "nunjucks": "_nunjucks_light",
  "obj": "_svg_1_light",
  "odata": "_odata_light",
  "ogg": "_audio_light",
  "ogv": "_video_light",
  "otf": "_font_light",
  "pddl": "_pddl_light",
  "pdf": "_pdf_light",
  "pem": "_lock_light",
  "php": "_php_light",
  "php.inc": "_php_light",
  "pipeline": "_pipeline_light",
  "pl": "_perl_light",
  "plan": "_plan_light",
  "pm": "_perl_light",
  "png": "_image_light",
  "pp": "_puppet_light",
  "prisma": "_prisma_light",
  "pro": "_prolog_light",
  "ps1": "_powershell_light",
  "psd": "_photoshop_light",
  "psm1": "_powershell_light",
  "purs": "_purescript_light",
  "pxm": "_image_light",
  "py": "_python_light",
  "pyi": "_python_light",
  "pyw": "_python_light",
  "r": "_R_light",
  "rb": "_ruby_light",
  "re": "_reasonml_light",
  "res": "_rescript_light",
  "resi": "_rescript_1_light",
  "rmd": "_R_light",
  "rs": "_rust_light",
  "s": "_asm_light",
  "sass": "_sass_light",
  "sbt": "_sbt_light",
  "scala": "_scala_light",
  "scss": "_sass_light",
  "sh": "_shell_light",
  "slang": "_crystal_embedded_light",
  "slide": "_go_light",
  "slim": "_slim_light",
  "slugignore": "_config_light",
  "smarty.tpl": "_smarty_light",
  "sol": "_ethereum_light",
  "soql": "_db_1_light",
  "spec.cjs": "_javascript_1_light",
  "spec.js": "_javascript_1_light",
  "spec.jsx": "_react_1_light",
  "spec.mjs": "_javascript_1_light",
  "spec.ts": "_typescript_1_light",
  "spec.tsx": "_react_1_light",
  "springbeans": "_spring_light",
  "sql": "_db_light",
  "sss": "_css_light",
  "stache": "_mustache_light",
  "static": "_config_light",
  "stl": "_svg_1_light",
  "styl": "_stylus_light",
  "stylelintignore": "_stylelint_1_light",
  "stylelintrc": "_stylelint_light",
  "stylelintrc.js": "_stylelint_light",
  "stylelintrc.json": "_stylelint_light",
  "stylelintrc.yaml": "_stylelint_light",
  "stylelintrc.yml": "_stylelint_light",
  "sublime-project": "_sublime_light",
  "sublime-workspace": "_sublime_light",
  "svelte": "_svelte_light",
  "svg": "_svg_light",
  "svgx": "_image_light",
  "swift": "_swift_light",
  "test.cjs": "_javascript_1_light",
  "test.js": "_javascript_1_light",
  "test.jsx": "_react_1_light",
  "test.mjs": "_javascript_1_light",
  "test.ts": "_typescript_1_light",
  "test.tsx": "_react_1_light",
  "tf": "_terraform_light",
  "tf.json": "_terraform_light",
  "tfvars": "_terraform_light",
  "tfvars.json": "_terraform_light",
  "tiff": "_image_light",
  "tmp": "_clock_1_light",
  "toml": "_config_light",
  "tpl": "_smarty_light",
  "tres": "_godot_2_light",
  "ts": "_typescript_light",
  "tscn": "_godot_3_light",
  "tsx": "_react_light",
  "ttf": "_font_light",
  "twig": "_twig_light",
  "vala": "_vala_light",
  "vapi": "_vala_light",
  "vue": "_vue_light",
  "wasm": "_wasm_light",
  "wat": "_wat_light",
  "wav": "_audio_light",
  "webm": "_video_light",
  "webp": "_image_light",
  "wgt": "_wgt_light",
  "woff": "_font_light",
  "woff2": "_font_light",
  "workspace": "_bazel_light",
  "xls": "_xls_light",
  "xlsx": "_xls_light",
  "xml": "_xml_light",
  "yaml": "_yml_light",
  "yml": "_yml_light",
  "zig": "_zig_light",
  "zip": "_zip_1_light",
  "zsh": "_shell_light",
}

export const SETI_FILE_NAMES: Record<string, string> = {
  "babel.config.cjs": "_babel",
  "babel.config.js": "_babel",
  "babel.config.json": "_babel",
  "bower.json": "_bower",
  "build": "_bazel",
  "build.bazel": "_bazel",
  "cargo.lock": "_rust",
  "cargo.toml": "_rust",
  "changelog": "_clock",
  "changelog.md": "_clock",
  "changelog.txt": "_clock",
  "changes": "_clock",
  "changes.md": "_clock",
  "changes.txt": "_clock",
  "cmakelists.txt": "_makefile_3",
  "compiling": "_license_1",
  "compiling.md": "_license_1",
  "compiling.txt": "_license_1",
  "contributing": "_license_2",
  "contributing.md": "_license_2",
  "contributing.txt": "_license_2",
  "copying": "_license",
  "copying.md": "_license",
  "copying.txt": "_license",
  "docker-healthcheck": "_docker_2",
  "eslint.config.js": "_eslint",
  "firebase.json": "_firebase",
  "geckodriver": "_firefox",
  "go.mod": "_go2",
  "go.sum": "_go2",
  "gruntfile.babel.js": "_grunt",
  "gruntfile.coffee": "_grunt",
  "gruntfile.js": "_grunt",
  "gulpfile": "_gulp",
  "gulpfile.js": "_gulp",
  "ionic.config.json": "_ionic",
  "ionic.project": "_ionic",
  "jenkinsfile": "_jenkins",
  "karma.conf.cjs": "_karma",
  "karma.conf.coffee": "_karma",
  "karma.conf.js": "_karma",
  "karma.conf.mjs": "_karma",
  "licence": "_license",
  "licence.md": "_license",
  "licence.txt": "_license",
  "license": "_license",
  "license.md": "_license",
  "license.txt": "_license",
  "mime.types": "_config",
  "mix": "_hex",
  "mvnw": "_maven",
  "npm-debug.log": "_npm_ignored",
  "omakefile": "_makefile_2",
  "package-lock.json": "_npm_1",
  "package.json": "_npm_1",
  "platformio.ini": "_platformio",
  "pom.xml": "_maven",
  "procfile": "_heroku",
  "qmakefile": "_makefile_1",
  "readme": "_info",
  "readme.md": "_info",
  "readme.txt": "_info",
  "rollup.config.js": "_rollup",
  "sass-lint.yml": "_sass",
  "stylelint.config.cjs": "_stylelint",
  "stylelint.config.js": "_stylelint",
  "stylelint.config.mjs": "_stylelint",
  "swagger.json": "_json_1",
  "swagger.yaml": "_json_1",
  "swagger.yml": "_json_1",
  "todo": "_todo",
  "todo.md": "_todo",
  "todo.txt": "_todo",
  "tsconfig.json": "_tsconfig",
  "version": "_clock",
  "version.md": "_clock",
  "version.txt": "_clock",
  "vite.config.cjs": "_vite",
  "vite.config.cts": "_vite",
  "vite.config.js": "_vite",
  "vite.config.mjs": "_vite",
  "vite.config.mts": "_vite",
  "vite.config.ts": "_vite",
  "webpack.common.cjs": "_webpack",
  "webpack.common.js": "_webpack",
  "webpack.common.mjs": "_webpack",
  "webpack.common.ts": "_webpack",
  "webpack.config.build.cjs": "_webpack",
  "webpack.config.build.js": "_webpack",
  "webpack.config.build.mjs": "_webpack",
  "webpack.config.build.ts": "_webpack",
  "webpack.config.cjs": "_webpack",
  "webpack.config.js": "_webpack",
  "webpack.config.mjs": "_webpack",
  "webpack.config.ts": "_webpack",
  "webpack.dev.cjs": "_webpack",
  "webpack.dev.js": "_webpack",
  "webpack.dev.mjs": "_webpack",
  "webpack.dev.ts": "_webpack",
  "webpack.prod.cjs": "_webpack",
  "webpack.prod.js": "_webpack",
  "webpack.prod.mjs": "_webpack",
  "webpack.prod.ts": "_webpack",
  "workspace": "_bazel",
  "workspace.bazel": "_bazel",
  "yarn.clean": "_yarn",
  "yarn.lock": "_yarn",
}

export const SETI_FILE_NAMES_LIGHT: Record<string, string> = {
  "babel.config.cjs": "_babel_light",
  "babel.config.js": "_babel_light",
  "babel.config.json": "_babel_light",
  "bower.json": "_bower_light",
  "build": "_bazel_light",
  "build.bazel": "_bazel_light",
  "cargo.lock": "_rust_light",
  "cargo.toml": "_rust_light",
  "changelog": "_clock_light",
  "changelog.md": "_clock_light",
  "changelog.txt": "_clock_light",
  "changes": "_clock_light",
  "changes.md": "_clock_light",
  "changes.txt": "_clock_light",
  "cmakelists.txt": "_makefile_3_light",
  "compiling": "_license_1_light",
  "compiling.md": "_license_1_light",
  "compiling.txt": "_license_1_light",
  "contributing": "_license_2_light",
  "contributing.md": "_license_2_light",
  "contributing.txt": "_license_2_light",
  "copying": "_license_light",
  "copying.md": "_license_light",
  "copying.txt": "_license_light",
  "docker-healthcheck": "_docker_2_light",
  "eslint.config.js": "_eslint_light",
  "firebase.json": "_firebase_light",
  "geckodriver": "_firefox_light",
  "go.mod": "_go2_light",
  "go.sum": "_go2_light",
  "gruntfile.babel.js": "_grunt_light",
  "gruntfile.coffee": "_grunt_light",
  "gruntfile.js": "_grunt_light",
  "gulpfile": "_gulp_light",
  "gulpfile.js": "_gulp_light",
  "ionic.config.json": "_ionic_light",
  "ionic.project": "_ionic_light",
  "jenkinsfile": "_jenkins_light",
  "karma.conf.cjs": "_karma_light",
  "karma.conf.coffee": "_karma_light",
  "karma.conf.js": "_karma_light",
  "karma.conf.mjs": "_karma_light",
  "licence": "_license_light",
  "licence.md": "_license_light",
  "licence.txt": "_license_light",
  "license": "_license_light",
  "license.md": "_license_light",
  "license.txt": "_license_light",
  "mime.types": "_config_light",
  "mix": "_hex_light",
  "mvnw": "_maven_light",
  "npm-debug.log": "_npm_ignored_light",
  "omakefile": "_makefile_2_light",
  "package-lock.json": "_npm_1_light",
  "package.json": "_npm_1_light",
  "platformio.ini": "_platformio_light",
  "pom.xml": "_maven_light",
  "procfile": "_heroku_light",
  "qmakefile": "_makefile_1_light",
  "readme": "_info_light",
  "readme.md": "_info_light",
  "readme.txt": "_info_light",
  "rollup.config.js": "_rollup_light",
  "sass-lint.yml": "_sass_light",
  "stylelint.config.cjs": "_stylelint_light",
  "stylelint.config.js": "_stylelint_light",
  "stylelint.config.mjs": "_stylelint_light",
  "swagger.json": "_json_1_light",
  "swagger.yaml": "_json_1_light",
  "swagger.yml": "_json_1_light",
  "todo": "_todo",
  "todo.md": "_todo",
  "todo.txt": "_todo",
  "tsconfig.json": "_tsconfig_light",
  "version": "_clock_light",
  "version.md": "_clock_light",
  "version.txt": "_clock_light",
  "vite.config.cjs": "_vite_light",
  "vite.config.cts": "_vite_light",
  "vite.config.js": "_vite_light",
  "vite.config.mjs": "_vite_light",
  "vite.config.mts": "_vite_light",
  "vite.config.ts": "_vite_light",
  "webpack.common.cjs": "_webpack_light",
  "webpack.common.js": "_webpack_light",
  "webpack.common.mjs": "_webpack_light",
  "webpack.common.ts": "_webpack_light",
  "webpack.config.build.cjs": "_webpack_light",
  "webpack.config.build.js": "_webpack_light",
  "webpack.config.build.mjs": "_webpack_light",
  "webpack.config.build.ts": "_webpack_light",
  "webpack.config.cjs": "_webpack_light",
  "webpack.config.js": "_webpack_light",
  "webpack.config.mjs": "_webpack_light",
  "webpack.config.ts": "_webpack_light",
  "webpack.dev.cjs": "_webpack_light",
  "webpack.dev.js": "_webpack_light",
  "webpack.dev.mjs": "_webpack_light",
  "webpack.dev.ts": "_webpack_light",
  "webpack.prod.cjs": "_webpack_light",
  "webpack.prod.js": "_webpack_light",
  "webpack.prod.mjs": "_webpack_light",
  "webpack.prod.ts": "_webpack_light",
  "workspace": "_bazel_light",
  "workspace.bazel": "_bazel_light",
  "yarn.clean": "_yarn_light",
  "yarn.lock": "_yarn_light",
}

export const SETI_DEFAULT_ID = "_default"
export const SETI_DEFAULT_ID_LIGHT = "_default_light"

