//! Build script for `k2-core`.
//!
//! Its only job: list the Garden catalog (`src/zen/garden-catalog/*.toml`,
//! prd-zen-user-widgets-v2 R5) as `GARDEN_CATALOG_SOURCES`, so adding a
//! ready-made Garden is a data file with no Rust edit. See
//! `src/zen/garden_catalog.rs`.

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let dir = manifest.join("src/zen/garden-catalog");
    println!("cargo:rerun-if-changed=build.rs");
    // A directory path makes cargo rerun on any change inside it (add,
    // remove, edit).
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut files: Vec<(String, PathBuf)> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("{}: {e}", dir.display()))
        .map(|e| e.unwrap_or_else(|e| panic!("{}: {e}", dir.display())).path())
        .filter(|p| p.extension().is_some_and(|x| x == "toml"))
        .map(|p| {
            let name = p.file_name().and_then(|n| n.to_str()).expect("catalog file names are UTF-8").to_string();
            (name, p)
        })
        .collect();
    files.sort();

    let mut out = String::from(
        "/// Every `src/zen/garden-catalog/*.toml`, sorted by file name: `(file, TOML)`.\n\
         /// Generated by `build.rs`.\n\
         pub const GARDEN_CATALOG_SOURCES: &[(&str, &str)] = &[\n",
    );
    for (name, path) in &files {
        let path = path.to_str().expect("catalog paths are UTF-8");
        writeln!(out, "    ({name:?}, include_str!({path:?})),").expect("write to String");
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("zen_garden_catalog.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("{}: {e}", dest.display()));
}
