/* AUTO-GENERATED by scripts/build-styles.mjs — DO NOT EDIT BY HAND.
 * Source of truth: styles/<id>/{style.json,tokens.json,palettes/*.json}.
 * Rebuild with: bun run styles:build (and commit the result). */

export type StyleScheme = 'dark' | 'light'

/** Matches KesselColorsConfig (src/renderer/kessel/config.ts). */
export interface StyleTerminalColors {
  foreground: number
  background: number
  palette: readonly number[]
  cursor: { text: number | null; cursor: number }
  selection: { text: number | null; background: number }
}

export interface StylePaletteMeta {
  id: string
  name: string
  schemes: readonly StyleScheme[]
  swatch: { bg: string; surface: string; elevated: string; accent: string; textPrimary: string; border: string }
  terminal: StyleTerminalColors
}

export interface StyleMeta {
  id: string
  name: string
  author: string
  description: string
  defaultPalette: string
  defaultPalettes: Partial<Record<StyleScheme, string>>
  capabilities: { gaps: boolean; backdrop: boolean; schemes: readonly StyleScheme[] }
  gapPresets: readonly string[]
  palettes: readonly StylePaletteMeta[]
}

export const DEFAULT_STYLE_ID = "square"

export const STYLES: readonly StyleMeta[] = [
  {
    "id": "glass",
    "name": "Liquid Glass",
    "author": "Alakazam Labs",
    "description": "Experimental preview — frosted instrument glass over a deep ambient canvas. Chrome floats as translucent cards; terminals stay pure and opaque.",
    "defaultPalette": "obsidian",
    "defaultPalettes": {
      "dark": "obsidian"
    },
    "capabilities": {
      "gaps": false,
      "backdrop": true,
      "schemes": [
        "dark"
      ]
    },
    "gapPresets": [],
    "palettes": [
      {
        "id": "obsidian",
        "name": "Obsidian",
        "schemes": [
          "dark"
        ],
        "swatch": {
          "bg": "#0a0c12",
          "surface": "rgba(16, 20, 32, 0.58)",
          "elevated": "rgba(30, 36, 56, 0.62)",
          "accent": "#5aa2ff",
          "textPrimary": "#eef1f8",
          "border": "rgba(255, 255, 255, 0.09)"
        },
        "terminal": {
          "foreground": 15133170,
          "background": 658450,
          "palette": [
            1053468,
            16735581,
            4054148,
            16760899,
            5939967,
            11897599,
            5099745,
            12831193,
            5989240,
            16744576,
            7268256,
            16765286,
            8567039,
            13347583,
            8315887,
            15922684
          ],
          "cursor": {
            "text": null,
            "cursor": 15133170
          },
          "selection": {
            "text": null,
            "background": 2765648
          }
        }
      }
    ]
  },
  {
    "id": "square",
    "name": "Square",
    "author": "Alakazam Labs",
    "description": "K2's original look: flat, flush, zero-radius, 1px hairline dividers, everything touching. The reference implementation of the Style contract — bound to the app's historical values exactly.",
    "defaultPalette": "charcoal",
    "defaultPalettes": {
      "dark": "charcoal",
      "light": "paper"
    },
    "capabilities": {
      "gaps": true,
      "backdrop": false,
      "schemes": [
        "dark",
        "light"
      ]
    },
    "gapPresets": [
      "regular",
      "spacious"
    ],
    "palettes": [
      {
        "id": "charcoal",
        "name": "Charcoal",
        "schemes": [
          "dark"
        ],
        "swatch": {
          "bg": "#0a0a0a",
          "surface": "#141414",
          "elevated": "#1e1e1e",
          "accent": "#3b82f6",
          "textPrimary": "#e4e4e7",
          "border": "#2a2a2a"
        },
        "terminal": {
          "foreground": 14737632,
          "background": 657930,
          "palette": [
            0,
            13369344,
            5151238,
            12886016,
            3433892,
            7688315,
            432282,
            13883343,
            5592915,
            15673641,
            9101876,
            16574799,
            7512015,
            11370408,
            3465954,
            15658732
          ],
          "cursor": {
            "text": null,
            "cursor": 14737632
          },
          "selection": {
            "text": null,
            "background": 4473924
          }
        }
      },
      {
        "id": "paper",
        "name": "Paper",
        "schemes": [
          "light"
        ],
        "swatch": {
          "bg": "#fafafa",
          "surface": "#f1f1f2",
          "elevated": "#e8e8ea",
          "accent": "#2563eb",
          "textPrimary": "#1c1c1f",
          "border": "#d9d9de"
        },
        "terminal": {
          "foreground": 1842207,
          "background": 16448250,
          "palette": [
            1842207,
            12131356,
            4157217,
            9724416,
            2972318,
            7031413,
            292474,
            9342616,
            5592414,
            14427686,
            5147178,
            11893504,
            3433892,
            9265050,
            430228,
            657930
          ],
          "cursor": {
            "text": null,
            "cursor": 1842207
          },
          "selection": {
            "text": null,
            "background": 13224399
          }
        }
      }
    ]
  }
]

export function getStyle(id: string): StyleMeta | undefined {
  return STYLES.find((s) => s.id === id)
}

export function getPalette(styleId: string, paletteId: string): StylePaletteMeta | undefined {
  return getStyle(styleId)?.palettes.find((p) => p.id === paletteId)
}
