/* AUTO-GENERATED by scripts/build-styles.mjs — DO NOT EDIT BY HAND.
 * Source of truth: styles/<id>/{style.json,tokens.json,palettes/*.json}.
 * Rebuild with: bun run styles:build (and commit the result). */

export type StyleScheme = 'dark' | 'light'

/** Matches KesselColorsConfig (src/renderer/kessel/config.ts). */
export interface StyleTerminalColors {
  foreground: number
  background: number
  palette: readonly number[]
  cursor: { text: number | null; cursor: number }
  selection: { text: number | null; background: number }
}

export interface StylePaletteMeta {
  id: string
  name: string
  schemes: readonly StyleScheme[]
  swatch: { bg: string; surface: string; elevated: string; accent: string; textPrimary: string; border: string }
  terminal: StyleTerminalColors
}

/** A user-adjustable knob the style's manifest advertises. The dial
 *  writes `token` as an inline custom property on <html>; values are
 *  per-user (localStorage `k2.dial.<styleId>.<dialId>`). */
export interface StyleDialMeta {
  id: string
  label: string
  /** CSS custom property the dial writes, e.g. --material-blur. */
  token: string
  min: number
  max: number
  step?: number
  /** Unit appended when writing the token, e.g. 'px'. */
  unit?: string
  /** Resting value when the user hasn't adjusted the dial. */
  default?: number
}

export interface StyleMeta {
  id: string
  name: string
  author: string
  description: string
  defaultPalette: string
  defaultPalettes: Partial<Record<StyleScheme, string>>
  capabilities: { gaps: boolean; backdrop: boolean; schemes: readonly StyleScheme[] }
  gapPresets: readonly string[]
  dials: readonly StyleDialMeta[]
  palettes: readonly StylePaletteMeta[]
}

export const DEFAULT_STYLE_ID = "square"

export const STYLES: readonly StyleMeta[] = [
  {
    "id": "bezel",
    "name": "Bezel",
    "author": "Alakazam Labs",
    "description": "Experimental preview — layered-ring cards on warm graphite: hairline, bright gap, outer line. Tactile keycap controls, zite-gold accent.",
    "defaultPalette": "graphite",
    "defaultPalettes": {
      "dark": "graphite"
    },
    "capabilities": {
      "gaps": false,
      "backdrop": false,
      "schemes": [
        "dark"
      ]
    },
    "gapPresets": [],
    "dials": [],
    "palettes": [
      {
        "id": "graphite",
        "name": "Graphite",
        "schemes": [
          "dark"
        ],
        "swatch": {
          "bg": "#100f0e",
          "surface": "#1b1a18",
          "elevated": "#252320",
          "accent": "#ffc700",
          "textPrimary": "#eae6de",
          "border": "rgba(255, 255, 255, 0.07)"
        },
        "terminal": {
          "foreground": 15065560,
          "background": 1052430,
          "palette": [
            1512980,
            15619927,
            5226351,
            15054908,
            7317464,
            12618436,
            6078648,
            13222580,
            7301471,
            15959429,
            8049812,
            15649124,
            9683176,
            14002392,
            8705485,
            16052455
          ],
          "cursor": {
            "text": null,
            "cursor": 16762624
          },
          "selection": {
            "text": null,
            "background": 3815215
          }
        }
      }
    ]
  },
  {
    "id": "glass",
    "name": "Liquid Glass",
    "author": "Alakazam Labs",
    "description": "Experimental preview — frosted instrument glass over a deep ambient canvas. Chrome floats as translucent cards; terminals stay pure and opaque.",
    "defaultPalette": "obsidian",
    "defaultPalettes": {
      "dark": "obsidian"
    },
    "capabilities": {
      "gaps": false,
      "backdrop": true,
      "schemes": [
        "dark"
      ]
    },
    "gapPresets": [],
    "dials": [
      {
        "id": "frost",
        "label": "Frost",
        "token": "--material-blur",
        "min": 0,
        "max": 30,
        "step": 1,
        "unit": "px",
        "default": 18
      }
    ],
    "palettes": [
      {
        "id": "obsidian",
        "name": "Obsidian",
        "schemes": [
          "dark"
        ],
        "swatch": {
          "bg": "#0a0c12",
          "surface": "rgba(16, 20, 32, 0.58)",
          "elevated": "rgba(30, 36, 56, 0.62)",
          "accent": "#5aa2ff",
          "textPrimary": "#eef1f8",
          "border": "rgba(255, 255, 255, 0.09)"
        },
        "terminal": {
          "foreground": 15133170,
          "background": 658450,
          "palette": [
            1053468,
            16735581,
            4054148,
            16760899,
            5939967,
            11897599,
            5099745,
            12831193,
            5989240,
            16744576,
            7268256,
            16765286,
            8567039,
            13347583,
            8315887,
            15922684
          ],
          "cursor": {
            "text": null,
            "cursor": 15133170
          },
          "selection": {
            "text": null,
            "background": 2765648
          }
        }
      }
    ]
  },
  {
    "id": "square",
    "name": "Square",
    "author": "Alakazam Labs",
    "description": "K2's original look: flat, flush, zero-radius, 1px hairline dividers, everything touching. The reference implementation of the Style contract — bound to the app's historical values exactly.",
    "defaultPalette": "charcoal",
    "defaultPalettes": {
      "dark": "charcoal",
      "light": "paper"
    },
    "capabilities": {
      "gaps": true,
      "backdrop": false,
      "schemes": [
        "dark",
        "light"
      ]
    },
    "gapPresets": [
      "regular",
      "spacious"
    ],
    "dials": [],
    "palettes": [
      {
        "id": "charcoal",
        "name": "Charcoal",
        "schemes": [
          "dark"
        ],
        "swatch": {
          "bg": "#0a0a0a",
          "surface": "#141414",
          "elevated": "#1e1e1e",
          "accent": "#3b82f6",
          "textPrimary": "#e4e4e7",
          "border": "#2a2a2a"
        },
        "terminal": {
          "foreground": 14737632,
          "background": 657930,
          "palette": [
            0,
            13369344,
            5151238,
            12886016,
            3433892,
            7688315,
            432282,
            13883343,
            5592915,
            15673641,
            9101876,
            16574799,
            7512015,
            11370408,
            3465954,
            15658732
          ],
          "cursor": {
            "text": null,
            "cursor": 14737632
          },
          "selection": {
            "text": null,
            "background": 4473924
          }
        }
      },
      {
        "id": "paper",
        "name": "Paper",
        "schemes": [
          "light"
        ],
        "swatch": {
          "bg": "#faf8f3",
          "surface": "#f2efe8",
          "elevated": "#e7e2d7",
          "accent": "#255a92",
          "textPrimary": "#221e15",
          "border": "#dcd5c6"
        },
        "terminal": {
          "foreground": 2235925,
          "background": 16447731,
          "palette": [
            2235925,
            11740702,
            2583357,
            10119688,
            2448018,
            8080006,
            1011824,
            9603450,
            5985349,
            13645864,
            3115598,
            12092170,
            3699627,
            9724063,
            1214602,
            657414
          ],
          "cursor": {
            "text": null,
            "cursor": 2235925
          },
          "selection": {
            "text": null,
            "background": 14275264
          }
        }
      }
    ]
  }
]

export function getStyle(id: string): StyleMeta | undefined {
  return STYLES.find((s) => s.id === id)
}

export function getPalette(styleId: string, paletteId: string): StylePaletteMeta | undefined {
  return getStyle(styleId)?.palettes.find((p) => p.id === paletteId)
}
